### ISSUE TITLE
Możliwość dodawania załączników w wiadomościach prywatnych

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#105]
Obecnie w wiadomościach prywatnych można dodać załączniki, tylko poprzez Ctrl+V (wklejenie ze schowka). 

Należy dodać możliwość wstawiania innych załączników (np. poprzez drag'n'drop) czy metodą tradycyjną.

**Comment by furious-programming** [comment]
Aby ujednolicić obsługę załączników, należy wykonać to tak samo, jak ma to miejsce w module tworzenia/edycji posta. Czyli m.in. dodać zakładkę **załączniki**, dodać możliwość kliknięcia na załącznik w celu dodania specjalnej frazy do treści wiadomości (w miejsce kursora) itd.
