### ISSUE TITLE
przyciski do operacji związanych z kodem oraz numerowanie linii

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#109]
Warto było by dodać wąski pasek ponad polem kodu, zawierający przyciski do popularnych operacji związanych z kodem; Głównie chodzi o opcję **Kopiuj**, jednak aby pasek nie był pusty, można by też upchnąć w nim opcje dotyczące kolorowania składni;

Ewentualnie, jeśli przyciski do wyboru języka (do kolorowania składni) mają już swoje miejsce to wystarczy jeden przycisk do samego kopiowania, np. w prawym górnym rogu, aby nie przeszkadzał;

Przyda się też numerowanie linii kodu - łatwiej było by opisywać problemy, wskazując numer linii, zamiast przeklejać omawianą linijkę.

**Comment by adam-boduch** [comment]
Kolorowanie skladnii nie zostalo zaimplementowane w nowej wersji. Mam wrazenie, ze nie jest to zbyt uzyteczna funkcja.

Natomiast jezeli chodzi o kopiowanie, to kiedys  bylo, ale niestety byly problemy ze skopiowaniem kodu poprzez zaznaczenie (tylko na niektorych przegladarkach) i niestety trzeba bylo te funkcje wylaczyc.

**Comment by furious-programming** [comment]
Czyli uważasz, że za dużo będzie problemów z kopiowaniem tekstu i lepiej nie dodawać?

Kolorowania składni nie musi być.

**Comment by adam-boduch** [comment]
W moim poprzednim poście niezbyt dokładnie się wyraziłem. Kopiowanie całego listingu kodu to całkiem fajna funkcjonalność i można dodać taką opcję (np. kopiowanie po naciśnięciu przycisku). 

Problem z kopiowaniem kodu poprzez zaznaczenie występował kiedyś gdy dodaliśmy numerowanie linii kodu. Wtedy gdy zaznaczałeś kod, do schowka kopiowały się też numery linii. Być może obecnie, ten problem nie występuje na nowszych przeglądarkach, nie wiem...

**Comment by furious-programming** [comment]
Co do drugiej części - a to przypadkiem nie zależy od sposobu wyświetlania kodu?

Np. na **pastebin.com** jest numerowanie linii, ale zaznaczanie kodu nie powoduje zaznaczenia numerów linii, przez co one nie zostają skopiowane. Tak samo wygląda to na **ideone.com**, więc da się to zrobić dobrze.

Przy czym stara **Opera**, podczas kopiowania tak zaznaczonego kodu, dorzuca puste linie po każdej linii kopiowanego tekstu. Ten dziwny efekt nie występuje np. w nowym **Firefox**.

**Comment by PleaseDontKillMe** [comment]
Nie sądzicie faktycznie, że skoro 4p to najlepsze polskie forum o programowaniu, to powinno mieć przynajmniej jakiś prosty sposób do edycji kodu w postach?

To co mi by się podobało to to, że gdybym zaznaczył kod
![image](https://cloud.githubusercontent.com/assets/13367735/21802642/dc5ea96c-d726-11e6-9735-3c3dd2242d82.png)

i wcisnął TAB, to miłą zmianą byłoby

![image](https://cloud.githubusercontent.com/assets/13367735/21802660/ef740c36-d726-11e6-8d59-34ba02ded088.png)

**Comment by adam-boduch** [comment]
Ciezko powiedziec. Kiedys juz byla taka propozycja i czesc osob mowila, ze jednak tab powinien dzialac tak jak dziala domyslnie, czyli przechodzic do kolejnego pola.

Poki co dziala przycisk Shift+Tab, ktory robi wciecie. Nie dziala to jednak dobrze z zaznczonym blokiem kodu. 

W kazdym razie - dadalem watek z ankieta do dyskusji: https://4programmers.net/Forum/Coyote/282578-czy_klawisz_tab_powinien_tworzyc_wciecia_w_kodzie

**Comment by furious-programming** [comment]
Gdyby edytor treści posta nie był zwykłym polem edycyjnym, a umożliwiał wizualne formatowanie treści (**WYSIWYG**, jak **Word**) to może i byłby sens. Jednak czegoś takiego nie mamy, raczej na to się nie zanosi bo byłą by to skomplikowana do stworzenia kontrolka, więc lepiej, aby klawisz `Tab` służył do przerzucania focusa.

**Comment by Danon** [comment]
@furious-programming To pewnie tak na 250h pracy conajmniej ;)
