### ISSUE TITLE
Brak możliwości przywracania usuniętych postów.

### ISSUE THREAD

**Issue by DibbyDum** [adam-boduch/coyote#113]
Jako moderator lokalny (C# i .NET) nie mam możliwości przywrócenia usuniętych postów w swoich działach, nawet tych które sam usunąłem. Usunięty post jak i przycisk "Przywróć" są widoczne jednak po naciśnięciu przycisku "Przywróć" nic się nie dzieje.

**Comment by adam-boduch** [comment]
Jaka przegladarka?
Mozesz zobaczyc czy nie masz zadnych bledow JavaScript? W Chrome Ctrl+Shift+I otwiera narzedzia developerskie (zakladka Console).

**Comment by DibbyDum** [comment]
Firefox 49.0.2 po kliknięciu w przycisk nie pojawiają się żadne błędy w Console. Sprawdzałem przy wyłączonych Add-onach.
![console](https://cloud.githubusercontent.com/assets/21045790/20247650/6e52217e-a9d1-11e6-8694-d9354a5485ee.PNG)

PS Przywracanie działa pod Edge. Więc i prawdopodobnie pod Chrome ale tego nie sprawdzałem.
