### ISSUE TITLE
Zbyt mało widoczny przycisk "Zaakceptuj odpowiedź"

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#125]
_"Delikatnie nie odpowiada mi to, że approved answer jest mało widoczna"_

https://4programmers.net/Mikroblogi/View/15146#comment-15159

**Comment by KrzaQ** [comment]
Zdecydowanie preferowałem stary wygląd ✔

**Comment by adam-boduch** [comment]
Ok, w takim razie przywróci się starą ikonkę :)
