### ISSUE TITLE
"moje tagi" przestały być użyteczne - zniknął lub został schowany ich widok

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#134]
Stary link nie działa: http://forum.4programmers.net/?view=interesting

**Comment by msm-code** [comment]
(Ogólnie: co teraz robią "moje tagi"? Bo nie zauważyłem żeby na coś wpływały)

**Comment by adam-boduch** [comment]
@msm-code: podswietlaja watki zawierajace dany tag.

**Comment by KrzaQ** [comment]
Jak coś, to dla niektórych użytkowników jest to bardzo istotna regresja utrudniająca korzystanie z forum :))

**Comment by adam-boduch** [comment]
Wcześniej sprawdzałem statystyki kliknięć w poszczególne zakładki (z google analytics), ale coś mi mówi, że te statystyki nie było do końca wiarygodne ;)

**Comment by KrzaQ** [comment]
Możliwe, że nie jestem w większości :( Używałem wyłącznie `view=interesting`, oraz bezpośrednich linków z API wystawionego przez @msm-code. Na API na razie nie ma co liczyć, to fajnie by było mieć zbiorczy widok na obserwowane tagi.

**Comment by KrzaQ** [comment]
Czy to znaczy, że tej funkcjonalności (pokaż tematy z obserwowanych tagów) już nie będzie? :(

**Comment by KrzaQ** [comment]
Cofam poprzedni post. Teraz zauważyłem /Interesting ❤
