### ISSUE TITLE
Szybka edycja tagów dla moderatorów

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#143]
Dodanie przycisku edycji listy tagów w widoku wątku.

Po kliknięciu w przycisk tagi i przycisk edycji chowają się, a pojawia `Edit` do wpisywania tagów oraz przycisk zapisu zmian. Po kliknięciu w przycisk zapisu, `Edit` i przycisk zapisu chowają się, a pojawia poprawiona lista tagów i przycisk edycji.

**Comment by adam-boduch** [comment]
W zwiazku z ostatnimi zmianami szybka edycja tagow jest mozliwa.
