### ISSUE TITLE
Liczba nowych wiadomości nie chce zniknąć

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#144]
Będąc np. w widoku kategorii forum dostaję informację o nowej wiadomości. Obok ikonki koperty pojawia się liczba, np. `1`, co oznacza, że dostałem jedną wiadomość. Klikam na kopertę, pojawia się lista wiadomości - klikam w nową pozycję. Zostaję przeniesiony do listy wiadomości z danym użytkownikiem.

Pomimo tego, że strona całkowicie przeładowuje się w celu wyświetlenia listy wiadomości, liczba obok koperty nadal widnieje, choć nie powinna. Owtorzyłem nową wiadomość, więc liczba obok koperty nie odpowiada faktycznemu stanowi.

**Comment by adam-boduch** [comment]
Ok, ale znika jak przeladujesz strone?

**Comment by furious-programming** [comment]
Nie pamiętam - wyślij mi PM'kę to sprawdzę.
