### ISSUE TITLE
Prawdopodobny błąd z listą zalogowanych użytkowników

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#145]
Lista zalogowanych użytkownik np. w widoku głównej strony serwisu (z nowościami, popularnymi wpisami na mikroblogu, reputacją itd.) wydaje się o wiele za krótka. Jak to możliwe, że w popołudniowych godzinach (tak jak w chwili obecnej - godzina **17:00**), osób online jest **728**, w tym tylko **35** zarejestrowanych?

![users](https://cloud.githubusercontent.com/assets/8170730/21190326/aa2e1758-c221-11e6-80d2-68c1386eec14.png)

Tuż przed upgradem systemu, o tej godzinie lista zarejestrowanych użytkowników z podstawowymi uprawnieniami była **5x dłuższa**. Poza tym liczba **375 botów** wydaje się nierealna.

Trzeba sprawdzić, czy lista ta faktycznie generowana jest prawidłowo.

**Comment by adam-boduch** [comment]
Mozesz sprawdzic w panelu administracyjnym, tam masz szczegolowe informacje dotyczace zalogowanych.

**Comment by adam-boduch** [comment]
Ok, wiem o co chodzi. W starej wersji jezeli miales otwarta karte, to dalej widoczny byles jako zalogowany. Przegladarka laczyla sie co jakis czas z serwerem i "dawala znak zycia". Teraz tak nie jest i dlatego wydaje sie ze uzytkownikow jest tak malo. Po prostu jezeli nic nie robia przez 10 min, to sa traktowani jako userzy online.

Do poprawy! Dzieki za czujnosc!

**Comment by furious-programming** [comment]
Przywykłem do długich list użytkowników w środku dnia i tak krótka lista zupełnie mi nie pasowała, stąd zgłoszenie. No i też nigdy nie spotkałem się z sytuacją, kiedy to **Yahoo** odpalał **269** robotów do skanowania serwisu **;)**

**Comment by furious-programming** [comment]
Jest jeszcze jedna rzecz, jeśli chodzi o listę użytkowników w serwisie - boty wliczane są do ogólnej liczby **osób online**. Boty to nie są osoby, więc nie powinny być wliczane do zalogowanych i anonimowych użytkowników.

Szkoda że nie pamiętam jak to wyglądało w poprzedniej wersji serwisu...
