### ISSUE TITLE
Błędne filtrowanie wątków na liście wszystkich wątków

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#150]
Po spersonalizowaniu forum i poukrywaniu działów które mnie nie interesują, widok kategorii forum oraz lista działów w głównym menu `Forum` wyglądają prawidłowo, według ustawień użytkownika. Jeśli jednak przełączy się widok forum z zakładki `Kategorie` na `Wszystkie`, pojawiają się wątki ze wszystkich kategorii (również z działu `Kosz`!), zamiast tylko z tych odpowiadających ustawieniom użytkownika. To samo tyczy się listy wątków po przejściu do zakładki `Bez odpowiedzi` oraz `Moje`.

Robal - trzeba poprawić.

**Comment by adam-boduch** [comment]
Duplika z #132
