### ISSUE TITLE
Widzę subforum, do którego nie mam dostępu

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#153]
Konkretnie Moderatorzy / Administracja. Próba wejśca (chyba poprawnie) daje 401.

**Comment by adam-boduch** [comment]
Proszę, odezwij się do mnie na priv i napisz w którym miejscu to widzisz? Dołączysz screena?

**Comment by adam-boduch** [comment]
ok, już nie trzeba :)
