### ISSUE TITLE
Wołanie użytkownika @ nie działa ze znakami interpunkcyjnymi 

### ISSUE THREAD

**Issue by aurell** [adam-boduch/coyote#154]
@somekind. @somekinda @somekind'a

**Comment by adam-boduch** [comment]
za wyjątkiem odmiany, tj. `@admina`, `@adminowi` itp.

**Comment by KrzaQ** [comment]
Na poprzedniej wersji @user​a ⟵ [@, u, s, e, r, &zwsp;, a] wołało i ładnie pokazywało. Nie wiem czy to nowy bug czy też już jest poprawione powyższym commitem.
