### ISSUE TITLE
Powiadomienia nie znikają z innych tabów po ich odczytaniu.

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#155]
Wcześniej znikały.

**Comment by adam-boduch** [comment]
Masz na myśli licznik nowych wiadomości? Bo ten powinien znikać.

**Comment by KrzaQ** [comment]
Tak było, ale nie jestem w stanie teraz tego zreprodukować. Może coś z dłużej otwartymi tabami?

**Comment by Marooned-MB** [comment]
U mnie nie zniknęło powiadomienie o nowej wiadomości po odczytaniu jej na innym tabie.
