### ISSUE TITLE
Strona wizualna serwisu - za dużo kolorów i ich dziwne odcienie

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#159]
Pierwsza rzecz to fakt istnienia co najmniej dwóch odcieni koloru oliwkowego dla linków w serwisie. Większość linków posiada kolor oliwkowy (ciemny, taki jak w poprzedniej wersji serwisu), ale sporo z nich ma jakiś taki jasnozielony, drażniący oko. Trzeba by ujednolicić te kolory i wybrać jeden, najlepiej taki sam jak w poprzedniej wersji, czyli `#648017`, dla wszystkich linków w całym serwisie.

Druga sprawa to brak zdefiniowanego koloru linków w ramkach ostrzeżeń (np. z informacją o przeniesieniu lub zablokowaniu wątku), przez co link do profilu moderatora jest zielony, a nie powinien:

![frame](https://cloud.githubusercontent.com/assets/8170730/21243795/c0368b1c-c31a-11e6-92f9-8205fabe87e3.png)

Już nie wspominam o tym, że w powyższej ramce słówko `Newbie` powinno być - tak jak wcześniej - linkiem kierującym do źródłowej kategorii.

Trzecia sprawa jest związana z powyższą ramką - odcienie obramowania, tła i tekstu ramki są zdecydowanie inne niż w poprzedniej wersji. Te są zbyt jasne i nienajlepiej wyglądają. Również sugeruję powrót do poprzedniego schematu kolorów dla tych ramek.

Ostatnia sprawa to ramka z pozytywną informacją (taka zielona, np. po wysłaniu prywatnej wiadomości), która wizualnie odbiega od schematu - ma ciemne tło, obramowania nie posiada w ogóle. Wybrać jeden schemat dla ramek i jego się trzymać, a definiować jedynie kolory - dla ramki z informacją jasnozielone tło, a ciemnozielone obramowanie i tekst; dla ramki z ostrzeżeniem beżowe tło, a brązowe obramowanie i tekst, natomiast dla ramki błędu/odmowy, jasnoczerwone tło oraz ciemnoczerwone obramowanie i tekst. We wszystkich przypadkach kolor linków zawartych w tych ramkach musi odpowiadać kolorowi tekstu.

**Comment by adam-boduch** [comment]
Kolor linkow wewnatrz ostrzezen poprawilem.

Masz racje, w serwisie sa 2 odcienie linkow zielonych, tak jak w poprzedniej wersji.

Jezeli chodzi o kolor tla ostrzezen, to jest on taki sam jak poprzednio. Kolor obramowania i czcionki natomiast:

```
$state-warning-text:             #8a6d3b !default;
$state-warning-bg:               #fefae4 !default; 
$state-warning-border:           darken(adjust-hue($state-warning-bg, -10), 15%) !default;
```

**Comment by furious-programming** [comment]
> Masz racje, w serwisie sa 2 odcienie linkow zielonych, tak jak w poprzedniej wersji.

W tym właśnie rzecz, że w poprzedniej wersji był jeden odcień - `#648017` - a teraz są dwa, przy czym ten jasnozielony jest paskudny... **:P**

Do tego podświetlanie linków działa na odwrót - jasny normalny i ciemny po najechaniu kursorem. Poprzednio było dobrze, bo na odwrót niż teraz - jeden, ciemno-oliwkowy jako normalny i nieco jaśniejszy jako hover.

> Jezeli chodzi o kolor tla ostrzezen, to jest on taki sam jak poprzednio. Kolor obramowania i czcionki natomiast sa ustawione domyslnie przez bootstrap (framework css):

W poprzedniej wersji serwisu te ramki (trzy typy: informacja - zielona; ostrzeżenie - beżowa; błąd - czerwona) wyglądały lepiej, dlatego że były ciemniejsze (obramowanie i tekst) i nie raziły tak w oczy. No i grubość obramowania była mniejsza (`1px`), dzięki czemu wyglądały lepiej.

**Comment by adam-boduch** [comment]
>W tym właśnie rzecz, że w poprzedniej wersji był jeden odcień - #648017 - a teraz są dwa, przy czym ten jasnozielony jest paskudny... :P

![image](https://cloud.githubusercontent.com/assets/10835050/21266392/53a241c6-c3a6-11e6-931b-07cae2262544.png)
![image](https://cloud.githubusercontent.com/assets/10835050/21266427/7cce6318-c3a6-11e6-83ac-0a36be7ec4b9.png)

Tutaj wszędzie jest ten sam kolor, taki jak obecnie.

**Comment by furious-programming** [comment]
Sprawdzałem w narzędziach deweloperskich przeglądarki - znalazłem trzy różne odcienie o kodach podanych w poprzednim komentarzu.

**Comment by adam-boduch** [comment]
W serwisie sa dwa odcienie zielonego. Roznia sie nieznacznie. Domyslny zielony kolor jest zbyt jaskrawy np. na liscie watkow, w polaczeniu z fontem, ktory nie jest pogrubiony.
