### ISSUE TITLE
Niedziałający link do forum

### ISSUE THREAD

**Issue by ftldev** [adam-boduch/coyote#160]
W quick starcie miałem zapisanego linka jako:
http://4programmers.net/forum
Niestety nie działa on - dostaję 404. 

Link stał się on case sensitive, czyli działa http://4programmers.net/Forum

W efekcie myślałem, że cały serwis nie działa.

**Comment by furious-programming** [comment]
W quick start miałem link http://4programmers.net/logowanie, a teraz jest http://4programmers.net/Login. No cóż - zakładki trzeba sobie zaktualizować, choć to co faktycznie denerwuje to case sensitive adresów.

**Comment by adam-boduch** [comment]
Ok, zrobimy case insensitive dla adresow
