### ISSUE TITLE
Sugestia przywrócenia poprzedniego układu elementów komentarzy na blogu

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#164]
Jeszcze w wersji deweloperskiej sugerowałem przywrócenie układu elementów komentarzy na mikroblogu, ze względu na nieczytelną postać komentarza jako odpowiedzi na wpis (z dodaniem nicku użytkownika, któremu się odpowiada). W chwili obecnej, komentarz taki posiada dwa nicki pod rząd, a informacje dotyczące danego komentarza (data napisania i ilość głosów) są na dole wpisu, przez co ich umiejscowienie zależne jest od długości komentarza (i trzeba tych linków szukać).

Sugeruję zamianę takiego układu:

![current](https://cloud.githubusercontent.com/assets/8170730/21266561/15de68fa-c3a7-11e6-9059-9eb7cd33a04c.png)

na poprzedni, czyli taki:

![old](https://cloud.githubusercontent.com/assets/8170730/21266567/1ecf7936-c3a7-11e6-896c-fb7dddccedcd.png)

Był o wiele lepszy - czytelniejszy.

**Comment by adam-boduch** [comment]
Kwestia gustu. Mnie jednak podoba sie bardziej ta pierwsza wersja, taka jaka jest na fb.
