### ISSUE TITLE
Brak liczby obserwowanych użytkowników w informacjach profilowych

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#173]
Na stronie profilu danego użytkownika (https://4programmers.net/Profile/XXX) wcześniej były podane takie informacje (liczba **obserwujących** i **obserwowanych** profili) - teraz tego brakuje.

**Comment by adam-boduch** [comment]
Tak, nie przepisywalem tej funkcjonalnosci poki co. Nie znaczy ze zupelnie z niej rezygnuje. Chcialbym ja jednak bardziej rozbudowac, nie ograniczac tylko do mikroblogow.

**Comment by furious-programming** [comment]
Ale do jakich mikroblogów?

W poprzedniej wersji serwisu, pod linkiem który podałem, po prawej stronie była informacja z liczbą użytkowników obserwujących mój profil i z liczbą użytkowników, których sam informuję. Dotyczyło to całego serwisu, a nie tylko mikroblogów. Dzięki temu można było śledzić całą działalność danego użytkownika, dostając powiadomienia o jego nowych postach na forum czy wpisach na blogu.

Teraz takiej funkcji brakuje.

**Comment by adam-boduch** [comment]
Dokładnie, to dotyczyło tylko działalności na mikroblogach.
Tak,  będzie taka funkcjonalność, trzeba tylko przemyśleć jej działanie oraz funkcjonalność (aby ta funkcja była bardziej popularna i więcej osób z niej korzystało)

**Comment by furious-programming** [comment]
Ok, czyli wszystko jasne. Założę wątek na forum do przedyskutowania.
