### ISSUE TITLE
Nieczytelny zapis nagłówka listy użytkowników

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#174]
Zapis nagłówka listy użytkowników obecnych w serwisie jest strasznie pokręcony:

`%d osób online (gości: %d), w tym botów: %d, ludzi: %d`

Sugeruję nieco dłuższy format, ale bardziej czytelny i zrozumiały:

`%d użytkowników online, w tym zalogowanych: %d, anonimowych: %d, botów: %d`

**Comment by adam-boduch** [comment]
dla mnie moze byc :)

**Comment by furious-programming** [comment]
Nagłówek wygląda lepiej, ale jest pewien problem:

```delphi
517 użytkowników online, w tym zalogowanych 7, gości 510, botów: 385
```
Do **gości** wliczane są boty. Nagłówek ten powinien w takiej sytuacji wyglądać tak:

```delphi
517 użytkowników online, w tym zalogowanych 7, gości 125, botów: 385
```

**Comment by adam-boduch** [comment]
Poprawione. P.S. Poprawka z dwukropkami juz tez leci na gicie :)
