### ISSUE TITLE
Niedziałający link do wiadomości prywatnych w popupie

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#175]
Po kliknięciu w link zaznaczony na czerwono:

![pm](https://cloud.githubusercontent.com/assets/8170730/21327163/1d00eae8-c62e-11e6-96ad-14ae93f14c59.png)

nic się nie dzieje, a powinno mnie przekierować do głównej strony z wiadomościami prywatnymi. Sprawdzałem na starej **Operze** i na najnowszym **Firefox** - w obu przeglądarkach sytuacja wygląda tak samo.

**Comment by adam-boduch** [comment]
Poprawione
