### ISSUE TITLE
Szybkie odpowiadanie w tematach - tab, enter nie działa

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#181]
Jak w temacie. W poprzedniej wersji, o ile mi wiadomo, po editboksie następny w tab orderze był send button, a teraz nie jest.

**Comment by adam-boduch** [comment]
Mowa o szybkiej odpowiedzi? Powinno dzialac. U mnie dziala.

**Comment by KrzaQ** [comment]
Faktycznie. Musiałem coś źle próbować :|
