### ISSUE TITLE
Przy tworzeniu tematu odznaczenie "[ ] obserwuj" jest ignorowane

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#182]
Temat wciąż jest obserwowany po utworzeniu

**Comment by adam-boduch** [comment]
Hmm, sprawdzilem i ta funkcja dziala. Czy na pewno chodzi o utworzenie nowego watku?

**Comment by KrzaQ** [comment]
https://gfycat.com/TinyPortlyBlackmamba

**Comment by adam-boduch** [comment]
Dokladnie w ten sposob testowalem. Zakladajac nowy watek "odznaczylem" checkboxa obserwuj. Po dodaniu watka, nie byl on obserwowany (w prawym pasku narzedziowym widnialo, ze watek nie jest obserwowany).

**Comment by KrzaQ** [comment]
Hm, okej. W takim razie zmyliło mnie zaznaczone "obserwuj" przy poście - rozumiem, że dotyczy to posta, a nie tematu?

**Comment by adam-boduch** [comment]
aaa, tak, tak. mozna obserwowac watki (checkbox) ale i rowniez posty :) (powiadomienie o edycji, nowym komentarzu itp)
