### ISSUE TITLE
Powiadomienia, alerty na urzadzeniach mobilnych

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#186]
Poprawione wyswietlanie tych podstron na urzadzeniach mobilnych.

**Comment by silvuss** [comment]
@adam-boduch Dość lakonicznie. Co masz na myśli w tej issue?

**Comment by adam-boduch** [comment]
Juz chyba nieaktualne :)

**Comment by silvuss** [comment]
OK.
