### ISSUE TITLE
Błędny tooltip przycisku głosuj w microblogach

### ISSUE THREAD

**Issue by Artur92K** [adam-boduch/coyote#188]
Po zagłosowaniu na mikroblogu tooltip do przycisku głosuj wyświetla błędny opis.
![bledny tooltip](https://cloud.githubusercontent.com/assets/14106885/21382314/582023f4-c760-11e6-9402-cc357ac6fbfe.png)

**Comment by adam-boduch** [comment]
Jaka to jest przegladarka?
Czy nie ma zadnych bledow JavaScript? Sprawdz prosze w zakladce "Console", po nacisnieciu kombinacji Ctrl+Shift+I (na Chrome)

**Comment by Artur92K** [comment]
Firefox 50.1.0
Zrzut wszystkich zakładek z konsoli firefoxa: http://pastebin.com/u5jMH78f
Dla js`a mam tylko:

>Korzystanie z Mutation Events jest przestarzałe. Należy używać MutationObserver.  ContentVeil.js:2:4726
Strona wydaje się używać efektu pozycjonowania zależnego od przewijania. Może to nie działać właściwie. Pod adresem https://developer.mozilla.org/en-US/docs/Mozilla/Performance/ScrollLinkedEffects można znaleźć szczegółowe informacje i wskazówki jak pomóc.  4programmers.net

Na chrome wersja 55.0.2883.87 m (64-bit) to samo
błędy w konsoli: 

> http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://static.4programmers.net/img/facebook-image.png Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://www.google-analytics.com/analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
