### ISSUE TITLE
Niepoprawne łamanie linii na mikroblogu

### ISSUE THREAD

**Issue by Artur92K** [adam-boduch/coyote#193]
Łamanie linii działa niepoprawnie
![lamanie slow](https://cloud.githubusercontent.com/assets/14106885/21426502/8673eef8-c84f-11e6-852b-63c9f61ae189.png)

**Comment by adam-boduch** [comment]
Jaka to przegladarka?

**Comment by Artur92K** [comment]
FF 50.1
