### ISSUE TITLE
Niejednolitość obsługi i wyglądu edytorów treści materiałów w serwisie

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#197]
Podczas edycji komentarza do wpisu na mikroblogu, klawiszem `Esc` anuluje się wprowadzone zmiany, edytor zawartości znika i pojawia się tekst wpisu. Pod tym edytorem nie są wyświetlane przyciski `Anuluj` i `Zapisz`, tak jak ma to miejsce podczas edycji głównego wpisu na mikroblogu oraz podczas szybkiej edycji posta.

Zrobił się bajzel, bo każdy edytor obsługuje się inaczej - do tego przyciski pod nimi nazywają się inaczej, a do jego nie ma przycisków w ogóle... Sprawa dotyczy poniższych elementów:

1. edytora głównego wpisu na blogu - pojawiają się przyciski `Anuluj` i `Opublikuj`, ten drugi zmienić na `Zapisz`, dodać obsługę klawisza `Esc`,
2. edytora komentarza do wpisu na blogu - przycisków brak, więc należy dodać `Anuluj` i `Zapisz`, klawisz `Esc` jest obsługiwany,
3. edytora dla szybkiej edycji posta - są przyciski `Anuluj` i `Zapisz`, więc jedynie brakuje obsługi klawisza `Esc`,
4. edytora komentarza do postu - są przyciski `Anuluj` i `Zapisz komentarz`, ten drugi po prostu skrócić do `Zapisz`, dodać obsługę `Esc`,
5. edytora komentarza do artykułu - są przyciski `Anuluj` i `Zapisz`, brakuje obsługi `Esc`.

**Comment by adam-boduch** [comment]
Poki co ujednolicilem etykiety przyciskow.
