### ISSUE TITLE
Odwrotna kolejność przycisków do anulowania i akceptacji wyboru

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#198]
Nigdy wcześniej nie spotkałem się z taką kolejnością, aby pierwszym przyciskiem z lewej strony był przycisk do anulowania wyboru, a dopiero na końcu przycisk do akceptacji. W całym systemie jest to poodwracane, co jest nieintuicyjne i irytujące.

Sugeruję zmianę kolejności tych guzików, dlatego że ważniejszą i częściej używaną opcją jest akceptowanie wyboru czy akceptacja wprowadzonych zmian. Od aktualizacji systemu, okienek dialogowych czy przycisków pod edytorami użyłem już setki razy, a góra kilka razy potrzebowałem anulować okienko.

**Comment by adam-boduch** [comment]
Jezeli formularz jest wyrownany do lewej (tj. przycisk "wyslij"/"zapisz" znajduje sie po lewej stronie ekranu, to tak - najpierw powinien byc przycisk do wyslania, a potem do anulowania).

Jezeli natomiast przyciski wyrownane sa do prawej krawedzi to odwrotnie. Pierwszy przyklad z brzegu:

![image](https://cloud.githubusercontent.com/assets/10835050/21498620/7920efd4-cc2e-11e6-8ee3-0c413ba06ff2.png)


![image](https://cloud.githubusercontent.com/assets/10835050/21498625/80f92f78-cc2e-11e6-94a7-e703fa20bead.png)

**Comment by furious-programming** [comment]
To że **GitHub** ma przyciski rozmieszczone i pokolorowane po swojemu, nie oznacza, że należy z niego brać przykład. Przycisk akceptacji wyboru od zawsze był pierwszym z lewej, bez względu na wyrównanie. Tym bardziej, że cały kontent okien i innych miejsc wyświetlany jest od lewej do prawej.

IMO przyciski również powinny być wyświetlane od lewej do prawej, od najczęściej używanego po przycisk anulowania. Wyrównanie nie ma znaczenia, bo bez względu na to, czy przyciski są wyśrodkowane, czy dosunięte do prawej krawędzi, najważniejszy i tak jest przycisk akceptacji, więc najbardziej naturalnym dla niego miejscem jest lewa strona listy guzików.

Obecny układ jest tak samo niewygodny, jak ułożenie przycisków pionowo, gdzie najważniejszy przycisk byłby na samym dole listy, zamiast na samej górze.
