### ISSUE TITLE
Wewnętrzne linki do Kompendium mają pozmienianą wielkość liter

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#201]
Jeśli w treści posta wpiszę np. `[[Delphi/nil]]`, to w rezultacie otrzymam **[Nil](https://4programmers.net/Delphi/Nil)**, zapisane wielką literą. Zapewne dzieje się tak dlatego, że tytuł artykułu to właśnie `Nil`, a system poprawia to co wpisał użytkownik, tworząc link o takiej samej treści jak tytuł artykułu.

IMO system nie powinien poprawiać prawej części wewnętrznego linku. Według przyjętej konwencji nazewnictwa, słowa kluczowe pisze się małymi literami, więc podając link do kompendium, sam niechcący namawiam do łamania tej reguły.

**Comment by adam-boduch** [comment]
Trzeba użyć składni: `[[Delphi/nil|nil]]` -- wtedy etykieta linku  będzie wyświetlana małymi literami.

**Comment by furious-programming** [comment]
Czyli uważasz, że poprzedni sposób tworzenia linków był niepoprawny i obecny jest lepszy?
