### ISSUE TITLE
Ostatnia aktywność nie powinna pokazywać usuniętych wątków

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#202]
Wątki czy komentarze usunięte nie powinny pojawiać się na stronie głównej w "Ostatnia aktywność".

**Comment by furious-programming** [comment]
A wielkim problemem było by generowanie tej ostatniej aktywności na żywo, a nie co co ileś tam minut?

**Comment by adam-boduch** [comment]
Te informacje sa na zywo, ale nie w tym lezy problem. Po prostu nie po skasowaniu posta/komentarza, te dane nie sa stamtad usuwane :)

**Comment by furious-programming** [comment]
No to bug, bez dwóch zdań **:)**

**Comment by adam-boduch** [comment]
Zrobione.
