### ISSUE TITLE
Możliwość pominięcia tagowania wątku

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#204]
W kategorii forum, która wymaga tagowania, istnieje możliwość ominięcia podania tagów.

Trafiłem na przypadek wątku w kategorii **C++**, w której anonimowy użytkownik założył wątek i nie podał ani jednego tagu. Efektem jest brak możliwości szybkiej edycji pierwszego posta w wątku przez moderatora - nie da się zapisać wprowadzonych zmian (i system nie informuje dlaczego występuje odmowa zapisu). Dopiero po wejściu w pełną edycję posta i wciśnięciu przycisku `Zapisz`, system na czerwono podświetla pole edycyjne do podawania tagów i informuje, że co najmniej jeden tag jest wymagany.

Bug jak byk, który istniał już w poprzedniej wersji **Coyote**.

**Comment by adam-boduch** [comment]
Tak, to jest duplikat z #195 
Błąd jest poprawiony, dodana walidacja obecności tagu.
