### ISSUE TITLE
Nie ma informacji dokąd wątek został przeniesiony

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#206]
https://4programmers.net/Forum/C_i_C++/281783-fragment_kodu_pomocy

Link się nie zmienia. Jest tylko Kiedy, Kto i Dlaczego. W tym przypadku został przeniesiony do kosza, ale konia z rzędem temu, kto będzie w stanie to wywnioskować

**Comment by adam-boduch** [comment]
Bug zostal znaleziony i poprawiony jednak nie mozna tego naprawic w tym wskazanym watku.
