### ISSUE TITLE
Brak trimowania treści postów

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#210]
Treści postów w ogle nie są trimowane - białe znaku mogą się znajdować:

* na początku i na końcu każdego paragrafu,
* na początku i na końcu każdej linii kodu w znacznikach kolorujących składnię.

Białe znaki wymagane są jedynie na początku każdej linii kodu, znajdującego się w znacznikach dla kodu - albo w znacznikach ogólnych, bez kolorowania składni (tylko trzy bakticki), albo w znacznikach z określonym językiem (np. trzy backticki i słówko `delphi`).

Sugeruję więc, aby wdrożyć trimowanie **paragrafów** z obu stron, a także trimowanie **linii kodu** w znacznikach, tylko z prawej strony. Ułatwi to edytowanie postów, a także pozwoli zaoszczędzić nieco miejsca - użytkownicy bardzo często zostawiają mnóstwo białych znaków na koncach linii (również w pustych liniach), a także kopiują je z takich edytorów jak **Notepad++**, podczas kopiowania kodu.

**Comment by adam-boduch** [comment]
Nie wiem czy to jest na tyle istotny feature zważywszy na stopień skomplikowania, tj. nie jest to takie banalne zadanie. 

Póki co zostawiam, bo być może się ktoś zainteresuje tym zadaniem :)
