### ISSUE TITLE
Logowanie OAuth: mozliwosc scalania kont

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#217]
Jezeli uzytkownik ma juz wczesniej zarejestrowane konto u nas i potwierdzil adres e-mail, to powinno byc mozliwe zalogowanie porpzez - np. gmail. Obecnie system probuje stworzyc nowe konto ale rzuca bledem poniewaz adres email juz jest zajety.

**Comment by adamwojs** [comment]
Pojawi się problem jeśli ktoś chciałby połączyć konto 4programmers z kontem w serwisie trzecim, ale zarejestrowanym na inny adres e-mail. 

Może warto dodać w ustawianiach konta listę serwisów social media wraz z przyciskiem "Połącz konto". Przykład takiego rozwiązania wygrzebany gdzieś z odmętów google: https://support.newscred.com/hc/en-us/article_attachments/201584006/Newscred_Content_Marketing_Cloud.png . W przypadku logujemy się przez serwis trzeci gdzie mamy kolizje adresów e-mail wyświetlamy komunikat "Konto z adresem e-mail już istnieje. Jeśli chcesz połączyć swoje konto 4programmers z XYZ to przejdź do Moje konto > Ustawiania > "

**Comment by adam-boduch** [comment]
Masz racje, jednak na poczatku mozna zrobic scalanie kont w momencie gdy adres e-mail jest ten sam - u nas - oraz np. na facebooku.

To zadanie utworzylem pod wplywem jednego z uzytkownikow. Ma on od dawna konto na 4programmers.net, ma do niego przypisany adres e-mail (ktory jest potwierdzony). Chcialby sie zalogowac przy pomocy Google (gdzie adres e-mail jest te sam co u nas). Obecnie system to uniemozliwia.
