### ISSUE TITLE
upiększarka linków nie zawsze działa

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#218]
Następujące dwa linki:
`https://4programmers.net/Forum/Og%C5%82oszenia_drobne`
`https://4programmers.net/Pomoc/Forum_dyskusyjne/Dlaczego_nikt_nie_odpowiada_w_moim_w%C4%85tku`

W starej wersji forum były zamieniane na bezpośrednie linki do odpowiednich stron wraz ze zmianą treści linka na ładną (t.j. tytuł działu/tematu). Teraz tylko drugi jest zamieniany.

**Comment by adam-boduch** [comment]
Hmm, jaka przegladarka? Sprawdzilem na FF oraz Chrome i jest ok.

**Comment by KrzaQ** [comment]
Firefox

Jest:
![](http://i.imgur.com/mnqElA3.png)
![](http://i.imgur.com/o8Lz9CX.png)

Powinno być (i było):
![](http://i.imgur.com/vyhnI4i.png)

**Comment by KrzaQ** [comment]
Na innym komputerze z Pale Moon to samo. Nie spodziewałem się, że to może być problem po stronie klienta.

**Comment by adam-boduch** [comment]
aaa ok, juz wiem o co chodzi. nie zrozumialem problemu ;)

**Comment by adam-boduch** [comment]
Poprawione, tyle, ze musi sie cache odswiezyc :)
