### ISSUE TITLE
Niepoprawne sortowanie menu Forum

### ISSUE THREAD

**Issue by Koziolek** [adam-boduch/coyote#219]
W górnym menu `Forum` mamy jakieś dziwne sortowanie elementów.
![4p_forum](https://cloud.githubusercontent.com/assets/697126/21569843/c19a0ad6-cec0-11e6-96b4-178c4c63ab94.png)

**Comment by adam-boduch** [comment]
Hmm, cos sie zle zcachowalo :/ Teraz jest dobrze?

**Comment by Koziolek** [comment]
Tak
