### ISSUE TITLE
Emotikona nie jest parsowana jezeli ":)" jest na poczatku tekstu

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#220]
Jezeli ":)" znajduje sie na poczatku tekstu - nie jest parsowana

**Comment by furious-programming** [comment]
Dodam jeszcze, że emotka również nie zostanie zamieniona na obrazek, jeśli `:]` znajduje się na końcu posta - https://4programmers.net/Forum/1317713
