### ISSUE TITLE
Lista zalogowanych użytkowników - pomijanie bieżącego użytkownika

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#223]
Nie wiem czy ma to jakiś związek z ostatnimi zabiegami dotyczącymi listy użytkowników (usuwanie duplikatów, sortowanie), dlatego dodaję nowe zgłoszenie.

Dość często zdarza się, że jestem zalogowany, ale mój nick nie widnieje na liście zalogowanych:

![users](https://cloud.githubusercontent.com/assets/8170730/21577791/19fbcf32-cf68-11e6-8543-5cbbc97f501c.png)

Wygląda na bug.

**Comment by adam-boduch** [comment]
Tez mi sie to przytrafilo kilka razy.

**Comment by adam-boduch** [comment]
Poki co nie moglem znalezc bledu. Wydaje sie ze w kodzie wszystko jest w porzadku :(

**Comment by furious-programming** [comment]
No to niedobrze, bo problem faktycznie występuje.

Z tą lista jest więcej problemów - czasem klikam na zakładkę `Forum` i widzę listę kategorii, lista użytkowników zawiera przykładowo 30 zalogowanych użytkowników. Klikam po chwili znów w tę zakładkę i widzę pustą listę, klikam jeszcze raz i znów jest 30 użytkowników.

**Comment by adam-boduch** [comment]
Hmm, mysle, ze to ma zwiazek z adresem URL. Jezeli w URL jest sciezka `/Forum/Categories` to system szuka uzytkownikow ktorzy maja wyswietlona te strone. Trzeba by bylo dodac wyjatek na ten url.

**Comment by adam-boduch** [comment]
ok, ten bug występuje chyba tylko w przypadku pierwszego wejścia na stronę (gdy tworzona jest sesja). Zauważyłem, że po odświeżeniu strony już jest ok - tj. moj login widnieje na liscie.

**Comment by adam-boduch** [comment]
Powinno byc ok
