### ISSUE TITLE
LaTeX - jak teraz go użyć w poście?

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#224]
Jeśli się nie da ⟶ fajnie by było, żeby się dało.

**Comment by adam-boduch** [comment]
Ze wzgledu na wsteczna kompatybilnosc zachowana znacznik `<tex>`. Widze jednak ze na nowym serwerze nie dziala biblioteka do parsowania latex.

**Comment by adam-boduch** [comment]
Zrobione.
