### ISSUE TITLE
Brak spójności stylu dla znaczników "dfn"

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#229]
W artykule styl dla znacznika `<dfn>` wygląda w ten sposób:

![ok](https://cloud.githubusercontent.com/assets/8170730/21598912/1e777f76-d165-11e6-8c84-41b348b2729d.png)

natomiast w poście już nie - wygląda jak pochylony tekst, bez ikonki i kreski separatora u góry:

![bad](https://cloud.githubusercontent.com/assets/8170730/21598924/32d91254-d165-11e6-9302-d1e8a498bebd.png)

Przydałoby się określić styl dla tego znacznika w postach, aby treść w nim zawarta wyglądała tak samo jak w artykułach. Znacznik ten jest bardzo przydatny, więc pasowałoby, aby eksponował swoją zawartość.

**Comment by adam-boduch** [comment]
Myślę, że nie będzie z tym problemu :)
