### ISSUE TITLE
Łączenie postów nie uwzględnia załączników

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#245]
Jeśli łączymy dwa posty i ten drugi (późniejszy) posiada załączniki, to po połączeniu postów załączniki przepadają - nie są one kopiowane do wynikowego posta.

Podczas łączenia postów, trzeba brać pod uwagę kilka rzeczy:

* treść,
* załączniki,
* oceny,
* komentarze.

Wszystkie te elementy powinny być przenoszone z późniejszego posta do wcześniejszego.

Przy czym cała lista komentarzy z poźniejszego posta powinna być dodana na sam koniec listy komentarzy z posta wcześniejszego, tak aby nie wymieszały się i żeby nie utracić sensu dyskusji w tych komentarzach.

**Comment by adam-boduch** [comment]
Komentarze sa sortowane po dacie wiec nie ma tutaj mozliwosci manipulowaniem bo komentarz nie ma "kontekstu" czy pochodzi od mergowanego posta. Innymi slowy - nie jest to takie banalne w obecnie :P

**Comment by furious-programming** [comment]
Zawsze można zmanipulować daty wysłania komentarzy, w celu ich "posortowania" **:)**
