### ISSUE TITLE
Przerabianie sekwencji @nick na link nie zawsze jest wykonywane

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#247]
Czasem widuję, że parser nie przerabia sekwencji `@nick` na link do profilu użytkownika. Jeśli ktoś poda nieistniejącą nazwę użytkownika to nic dziwnego, jednak błąd występuje przy nazwach prawidłowych:

![nick](https://cloud.githubusercontent.com/assets/8170730/21754219/6ab3a798-d5fc-11e6-83eb-c3dc5e381a96.png)

Użytkownik o nicku `Althorion` istnieje w systemie, ale parser nie zamienił go na link.

Źródło: **[Dwie funkcje napisane w C](https://4programmers.net/Forum/1320362)**.

**Comment by adam-boduch** [comment]
Myślę, że to ma związek z zadaniem #227 
Poprawione w nowej wersji
