### ISSUE TITLE
Niepotrzebne parsowanie linków w backtickach

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#250]
Linki typu `[[foo]]` są parsowane nawet wtedy, gdy znajdują się wewnątrz backticków:

![links](https://cloud.githubusercontent.com/assets/8170730/21790166/9c238b34-d6da-11e6-8997-64a366fb420d.png)

Źródło: **[Obsługa JSON w Delphi XE7](https://4programmers.net/Forum/1279454)**.

**Comment by adam-boduch** [comment]
To już zostało poprawione. Po odświeżeniu cache powinno być ok :)

**Comment by furious-programming** [comment]
W dalszym ciągu problem występuje - cache nie jest tutaj winny. Nadal widzę link w znacznikach kodu, zarówno na **Operze** (będąc zalogowanym, nawet to wyczyszczeniu pamięci podręcznej), jak i na **Firefox** (widząc z anonima).

Czyli wychodzi na to, że problem nie został rozwiązany.

**Comment by adam-boduch** [comment]
https://4programmers.net/Forum/Delphi_Pascal/Submit/274551/1279454 Kliknij zakladke "Podglad". Zobaczysz, ze post zostanie dobrze sformatowany.

**Comment by furious-programming** [comment]
W podglądzie jest prawidłowo, ale w poście nadal nie jest; W normalnym widoku wątku, w kodzie znajduje się link i jest on widoczny zarówno na **Operze** (z której korzystam na co dzień do przeglądania serwisu), ale też na najnowszym **Firefox** (z którego do przeglądania serwisu nie korzystam), a także na tablecie z przeglądarką **CMBrowser**.

Więc nie ma znaczenia jaki system i jaka przeglądarka, bo problem faktycznie występuje. Jedynym miejscem gdzie wygląda prawidłowo jest podgląd wiadomości, ale w widoku wątku już nie.

**Comment by adam-boduch** [comment]
Zawartosc posta jest w cache, jak wygasnie to bedzie dobrze :P Mozesz zrobic test: zmodyfikowac tresc posta (dodajac np. jakis znak w tresci, aby post zostal ponownie scachowany).

**Comment by furious-programming** [comment]
Nie mogę zrobić edycji tego posta, bo wyrzuca mi błąd:

```
      4programmers.net
Whoops, looks like something
         went wrong.
```

**Comment by adam-boduch** [comment]
Dzięki za informacje. Poprawiłem buga, teraz post wyświetla się prawidłowo.

**Comment by furious-programming** [comment]
Teraz jest już dobrze - w poście i wodglądzie. Dobrze, że się upierałem `:)`
