### ISSUE TITLE
Brak możliwości edycji swojego posta jeżeli ktoś dodał do niego odpowiedź

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#255]
Taka możliwość powinni mieć jedynie użytkownicy z reputacją większą niż N pkt. Dla innych osób ta opcja powinna być wyłączona. Użytkownicy usuwają treść swoich postów "niszcząc" przez to wątki.

**Comment by furious-programming** [comment]
`n=100`?

**Comment by adam-boduch** [comment]
Moze byc i 100 :)
