### ISSUE TITLE
Brak blokady zabezpieczającej przez wielokrotnym wysłaniem posta lub peemki

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#270]
Piszę post, wciskam `Ctrl+Enter` lub klikam w przycisk `Zapisz` - trwa wysyłanie posta. Jeśli wyślę go kolejny raz, zanim strona zdoła się przeładować, post zostanie wysłany kilka razy - to samo jeśli chodzi o wiadomości prywatne.

Po drugie, każde kolejne wciśnięcie przycisku `Zapisz` lub kombinacji `Ctrl+Enter` przy wysyłaniu posta dodaje kolejną animowaną ikonkę do treści przycisku:

![save](https://cloud.githubusercontent.com/assets/8170730/21956591/b33e1a8e-da84-11e6-9110-b91957079dfb.png)

Trzeba dodać flagę określającą to czy została wywołana akcja i jeśli tak - kolejne akcje blokować.

**Comment by adam-boduch** [comment]
Hmm, mogę potwierdzić bug związany z Ctrl+Enter. Nie mogę jednak potwierdzić kilkakrotnego kliknięcia w przycisk, ponieważ pierwsze kliknięcie blokuje przycisk.

**Comment by furious-programming** [comment]
Gdyby to coś miało pomóc, to chodzi o **[ten post](https://4programmers.net/Forum/1322373)** i dwa kolejne usunięte.

Najwidoczniej miałem przez chwilę problem z połączeniem do sieci (albo inny problem z łączem) - wcisnąłem kombinację `Ctrl+Enter` raz i nic się nie działo. Wcisnąłem drugi raz po chwili i też nic się nie działo, ale zauważyłem, że druga ikonka animacji została dodana do przycisku, więc korzystając z okazji, wcisnąłem z 10 razy wymienioną kombinację i powstał przycisk jak na zrzucie wyżej. Ostatecznie post został wysłany trzy razy, choć łącznie wysłałem go 14 razy.
