### ISSUE TITLE
Brak podświetlenia wątku pomimo ulubionego tagu

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#289]
Wątek zawiera co najmniej jeden tag, który mam dodany do ulubionych, a pomimo tego wątek nie jest podświetlany na pomarańczowo:

![threads](https://cloud.githubusercontent.com/assets/8170730/22358905/0f05e4a6-e443-11e6-8e19-62530c03206d.png)

Usunąłem wszystkie tagi i dodałem ponownie - nadal jest to samo.

Poza tym wątek ma dodane **pięć tagów**, a wyświetlane są tylko trzy. Rozciągnięcie okna przeglądarki nawet na **2000px** w poziomie nic nie daje, więc jest to jakiś dziwny bug.

Chodzi o ten wątek - **[Połączenie odbc z MySQL](https://4programmers.net/Forum/Delphi_Pascal/283486-polaczenie_odbc_z_mysql)**.

**Comment by adam-boduch** [comment]
Tak, wyswietlane sa tylko 3 tagi z danego watku. Prawdopodobnie bug ma z tym zwiazek.
