### ISSUE TITLE
Pusta linia wymagana pod cytatem

### ISSUE THREAD

**Issue by twono** [adam-boduch/coyote#290]
Jeśli mam cytat zaczynający się od `>` w jednej linii, to nie mogę od razu pisać w następnej linii, bo to będzie traktowane jako cytat mimo braku `>`. Muszę wstawić jedną pustą linię i dopiero wtedy mogę dodać własny tekst.
Subiektywnie jest zbyt duży odstęp między cytatem a tekstem pod nim (nie będący cytatem). To jest szczególnie denerwujące gdy mam 
```
cytat
teskt do cytatu
cytat 
tekst do cytatu
```
Wtedy nie widać czy ten tekst pod cytatem odnosi się do cytatu nad nim czy pod nim. Wtedy muszę wstawić jakieś `<br />` żeby zrobić większy odstęp pod tekstem.

**Comment by adam-boduch** [comment]
To nie jest bład Coyote, ale wynika to se specyfikacji markdown. Tutaj, na github dziala to tak samo.

Jakby sie dluzej nad tym zastanowic, to jest to calkiem sensowne. Jezeli komentujesz jakis paragraf tekstu, to wystarczy postawic `>` przed pierwsza linijka. 

Tak jak napisales - aby zakonczyc cytat - stawiamy 2x enter.
