### ISSUE TITLE
Problematyczne obrazki miniaturek

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#291]
Pierwszym problemem jest możliwość załadowania obrazka praktycznie o dowolnych rozmiarach do miniaturki, co po pierwsze niczemu nie służy, bo obrazek ten i tak zawsze jest skalowany, przez co jego maksymalny rozmiar na ekranie to mniej więcej **148x148 px**, a po drugie, zbyt duży rozmiar obrazka pogarsza czas ładowania strony. Podczas ustawiania obrazka miniaturki system powinien go od razu skalować do maksymalnego rozmiaru, jaki wykorzystywany jest w serwisie (w największym rozmiarze jest to najpewniej miniaturka w postach).

Drugi problem dotyczy starej **Opery** i dymku typu **vcard**. Jeśli użytkownik wrzuci duży obrazek (przykładowo o wymiarach **600x600 px**), dymek ten wygląda potwornie:

![vcard](https://cloud.githubusercontent.com/assets/8170730/22397912/e54811b2-e57c-11e6-8c6b-45456ba08d2f.png)

Inny przykład:

![vcard2](https://cloud.githubusercontent.com/assets/8170730/22397987/a40e144c-e57e-11e6-983b-6de4997d9db9.png)

Jeszcze większa patologia.

Obrazek ten (czyli klasa `img-thumbnail`) nie posiada określonej maksymalnej szerokości w pikselach, przez co wszystkie obrazki miniaturek wyświetlane są bez jakiegokolwiek skalowania (zawsze w 100%). W przeglądarce **Firefox**, obrazek w **vcard** ma rozmiar nie przekraczający **80x80 px**, więc gdyby dodać do poniższego wpisu:

```css
#vcard-content .img-thumbnail { 
  border-bottom-left-radius: 0px;
  border-bottom-right-radius: 0px;
}
```
dodatkową pozycję, np. `max-width: 80px` to i na starej **Operze** dymek ten wyglądałby poprawnie.

**Comment by adam-boduch** [comment]
Przyczyna był bug powodujący, że obrazki nie były skalowane przy logowaniu poprzez google. Usunalem juz avatar Tomasza P. Natomiast jezeli chodzi o user noname, to juz napisalem do niego z prosba o ponowne wrzucenie avatara aby system mogl go przeskalowac ponownie.

**Comment by furious-programming** [comment]
Póki co wygląda dobrze, więc problem teoretycznie rozwiązany.
