### ISSUE TITLE
Brak obsługi niektórych znaczników formatowania tekstu w znacznikach <dfn>

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#292]
Wewnątrz znaczników `<dfn></dfn>` nie są obsługiwane wszystkie znaczniki do formatowania tekstu. Przykładowo znaczniki `[[Delphi/*]]` są obsługiwane, ale np. znaczniki `**` już nie są.

![dfn](https://cloud.githubusercontent.com/assets/8170730/22400395/bbe18b5a-e5b3-11e6-8382-6821303e6dbd.png)

Przydałoby się coś z tym zrobić.

**Comment by adam-boduch** [comment]
Markdown nie jest obsługiwany wewnątrz znaczników HTML :( Tak więc nie jest to bug, ale celowe działanie.

**Comment by furious-programming** [comment]
Dobrze chociaż, że HTML wewnątrz `<dfn>` jest parsowany... `:)`
