### ISSUE TITLE
Błąd 404 podczas próby oznaczenia wątku jako przeczytanego

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#299]
Sprawa wygląda nieciekawie, ale i jest specyficzna.

Dla przykładu, otwieram kategorię **Newbie**, strona pokazuje się na ekranie w całości, ale kursor informuje, że jeszcze trwa ładowanie (jakieś resztki). Klikam na pomarańczową ikonkę przy danym wątku:

![thread](https://cloud.githubusercontent.com/assets/8170730/22558471/1b644302-e96e-11e6-9054-579bfe59b6cf.png)

aby oznaczyć go jako przeczytanego i zostaję przekierowany na stronę błędu **404**:

![error](https://cloud.githubusercontent.com/assets/8170730/22558475/206b3d4c-e96e-11e6-8311-e463bb187963.png)

Na pasku widnieje adres `https://4programmers.net/Forum/Topic/Mark/283947`

Strona nie została usunięta - wątek istnieje i ma się dobrze. Problem w tym, że do oznaczenia wątku jako przeczytanego wymagane jest kompletne załadowanie strony, co nie miało miejsca w poprzedniej wersji serwisu - wcześniej obie funkcje (ładowanie strony i oznaczanie wątku jako przeczytanego) działały niezależnie.

**Comment by adam-boduch** [comment]
Zgadza się. Obecnie JavaScript przeniesiony został na dół strony aby przyspieszyć ładowanie. Oznacza to, że może zaistnieć taka sytuacja jak mówisz. 

Rozwiązanie: usunięcie atrybutu `href` z linka, na rzecz innego - np. - `ajax-href` lub podobny. Wtedy kliknięcie nie spowoduje przekierowania do czasu załadowania JS.

**Comment by furious-programming** [comment]
A gdyby wszystkie skrypty przenieść na górę strony, tak aby ładowały się jako pierwsze?

IMO bez względu na ich umiejscowienie, czas ładowania będzie taki sam. Przy czym jeśli skrypty ładować się będą na początku to nie będzie problemów z błędami. Co najwyżej nieco dłużej widoczna będzie pusta zawartość przeglądarki.

**Comment by adam-boduch** [comment]
Wlasnie zalecane jest przeniesienie ich niezej, ze wzgledu na wydajnosc i czas ladowania :)

**Comment by furious-programming** [comment]
Przecież strona i tak będzie się ładować tyle samo czasu, bez względu na umiejscowienie ładowania skryptów. Nic szybciej nie załaduje się, jeśli skrypty będą na końcu - co najwyżej strona wcześniej pokaże się na ekranie, ale to nie oznacza, że się załadowała `:)`

W starej wersji było inaczej i żadna funkcja nie rzucała w twarz błędem `404`, nawet jeśli strona nie załadowała się do końca. Oznaczanie wątków jako przeczytanych to nie jedyna funkcja, która zwraca błąd zanim załadują się skrypty. Inne równie problematyczne to choćby plusowanie postów czy oznaczanie ich jako przeczytanych. Założę się, że takich przypadków jest o wiele więcej.

Rozwiązaniem jest albo przeniesienie skryptów na górę i ładowanie ich na początku, albo zabezpieczenie wszystkich funkcji, tak aby nie kierowały do strony z błędem.

**Comment by adam-boduch** [comment]
Zaufaj mi - jest dobrze tak jak jest ;)
Przenoszac skrypty na gore, przegladarka wykonuje request do serwera i wstrzymuje dalsze ladowanie/pokazywanie tresci, a wlasnie chodzi o to, zeby pokazac tresc, reszta moze sie dociagnac pozniej.

**Comment by furious-programming** [comment]
To raczej nie powinno nikogo dziwić `:)`

Czyli rozwiązanie pozostaje jedno - zabezpieczyć istniejący kod przed przekierowywaniem na stronę błędu.
