### ISSUE TITLE
C++: raw string literale nie są poprawnie kolorowane

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#301]
Przykład: https://4programmers.net/Forum/1330218

`R"delim( cokolwiek nie delim  )delim"` to raw string literal. http://en.cppreference.com/w/cpp/language/string_literal (6)

Dodatkowo `constexpr` nie jest zaznaczone jako słowo kluczowe.

**Comment by adam-boduch** [comment]
Nie rozumiem. Czy chodzi tutaj o błąd w kolorowaniu składni? Bo jeżeli tak, to nie jest to błąd Coyote, ale zewnętrznej biblioteki. Raczej nie jest to do poprawienia, ponieważ jej kod nie jest już rozwijany :/

**Comment by KrzaQ** [comment]
Tak, chodzi o kod biblioteki. W takim razie słabo, ale faktycznie wiele nie zrobimy (chyba, żeby poszukać jakiejś alternatywy?)

**Comment by adam-boduch** [comment]
Prędzej czy później trzeba będzie zmienić :) Prawdopodobnie na jakiś parser napisany w JavaScript :/ bo innej alternatywy nie widzę...
