### ISSUE TITLE
Zamienić NPMa na Yarna

### ISSUE THREAD

**Issue by hauleth** [adam-boduch/coyote#302]
Dzięki temu będzie lockfile na zależności JSowe. To jest zmiana po stronie developerów i nie są potrzebne dodatkowe zmiany w repo (oprócz dodania `yarn.lock` do repo).

**Comment by adam-boduch** [comment]
Lockfile to niewatpliwie zaleta. Czyli yarn jest kompatybilny w stosunku do npm (format pliku `packages.json`)?

**Comment by hauleth** [comment]
Tak. Czasem zdarzają się problemy, ale to raczej z paczkami (czasem są jakieś pierdoły). Osobiście w pracy używamy i powoli (wymuszam) migrację na ww wszystkich projektach.
