### ISSUE TITLE
"Ostatnio" nie jest poprawnie odświeżane

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#303]
Użytkownik był dziś na forum. Napisał dziś temat/posta. "Ostatnio" wciąz pokazuje pół roku temu.
![][1]

[Temat][2]

[1]: http://i.imgur.com/GTBxxgt.png
[2]: https://4programmers.net/Forum/1332642

**Comment by adam-boduch** [comment]
No tak. To pole aktualizuje sie zakonczonej sesji. Powinno rowniez przy rozpoczetej sesji.

**Comment by KrzaQ** [comment]
Nie wiem czy tu powinienem pisać czy w nowym. Ja bym częściej to updatował (post? refresh strony?)

![][http://i.imgur.com/0mYsTV9.png]
Dziwnie to wygląda
