### ISSUE TITLE
`monospace` font w polu odpowiedzi

### ISSUE THREAD

**Issue by hauleth** [adam-boduch/coyote#304]
Z racji, że forum jest programistyczne to sądzę, że trochę by to ułatwiło :)

**Comment by adam-boduch** [comment]
Jakaś propozycja fontu? Bo chyba nie "courier new"? :)

**Comment by hauleth** [comment]
U siebie używam Hasklig, ale nie wszystkim może ona odpowiadać (ligatury). Alternatywy to Source Code Pro i Fira Mono (te jestem w stanie wymienić z pamięci) b

--
Łukasz Jan Niemier

Dnia 20 lut 2017 o godz. 08:24 adam-boduch <notifications@github.com> napisał(a):

**Comment by furious-programming** [comment]
Nie uznaję tego pomysłu za wartego uwagi. To że forum jest programistyczne, wcale nie oznacza, że każde pole do pisania musi być edytorem kodu. **GitHub** też jest stricte programistyczny, ale w każdym polu do pisania używa fontu o zmiennej szerokości znaków. Inne serwisy programistyczne czy fora również korzystają z "normalnych" fontów, więc nie widzę powodu, aby ustawiać jakiś monospace.

Sam font mono w niczym nie pomoże, a tylko niepotrzebnie wydłuży w pionie treść pisanego posta. Natomiast pisanie kodu bezpośrednio w przeglądarce i tak będzie niewygodne (nawet jeśli zostanie w nim ustawiony font monospace), bo w dalszym ciągu brakować będzie kolorowania składni, foldowania jego fragmentów i innych rzeczy, przydatnych podczas pisania.

Dlatego też uważam pomysł za bezsensowny, który w niczym nie poprawi jakości, natomiast z całą pewnością zmniejszy komfort pisania postów.

**Comment by adam-boduch** [comment]
Zamykam w związku z: https://4programmers.net/Forum/Coyote/285759-ankieta_czy_font_w_edytorze_powinien_byc_monospace (opinie oraz wyniki ankiety)
