### ISSUE TITLE
Linki do wewnętrznych artykułów nie są skracane w komentarzu

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#305]
W komentarzu do posta w kategorii **Newbie** linki nie są skracane:

https://4programmers.net/Forum/Newbie/284580-problem_z_funkcja_gettext#comment-339863

Ale w innym dziale, dla przykładu w **Coyote/Test** już są:

https://4programmers.net/Forum/Coyote/Test/281833-ach_ten_markdown?p=1332945#comment-339867

**Comment by adam-boduch** [comment]
Kurcze, wstawiłem identyczny komentarz i zadziałało poprawnie :|

**Comment by furious-programming** [comment]
Owszem, sprawdziłem teraz i wszystko gra. A ten co nie był skarany nadal nie jest... `;)`

**Comment by adam-boduch** [comment]
Otoz to. Tamten sobie siedzi w cache, tak wiec on sie tak od razu nie naprawi :) nie wiem tylko czemu to nie zadzialalo jak dodawales ten komentarz :|

**Comment by furious-programming** [comment]
Też nie wiem dlaczego. Próbowałem to poprawić, ale zawsze linki do tych artykułów wklejam z notatek **Opery**, więc na pewno nie ma w linku jakiejś literówki. To w sumie pierwszy taki przypadek - wcześniej nie spotkałem się z czymś takim.

Widać to jakiś bardzo egzotyczny bug i namierzenie go może być bardzo trudne.
