### ISSUE TITLE
Niepotrzebne parsowanie linku do YouTube

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#306]
Jeśli link wrzucony jest bezpośrednio do posta to w tym miejscu zostanie załadowane okienko z **YouTube** z możliwością oglądania wideo, przykład:

```
https://www.youtube.com/watch?v=SC9ybxMDGlE
```
Jednak jeśli wrzuci się link w markdownowe znaczniki linku, aby móc określić treść linku, to mimo wszystko parser zamienia całą frazę na ramkę z filmem. Przykład:

```
[treść linku](https://www.youtube.com/watch?v=SC9ybxMDGlE)
```
Według mnie to zachowanie jest nieprawidłowe i link powinien być zamieniany na okienko z filmem jedynie w przypadku, gdy link wstawiony jest bezpośrednio do posta, bez jakichkolwiek znaczników.

Nie będzie to jakieś super proste w implementacji, jednak mimo wszystko warto rozróżniać te sytuacje.

**Comment by adam-boduch** [comment]
Masz racje. Taka skladnia rowniez nie powinna byc zamieniana na widoe: `<a href="https://www.youtube.com/watch?v=SC9ybxMDGlE">test</a>`
