### ISSUE TITLE
Przycisk "Komentuj" (pod postem) widoczny dla anonimowych użytkowników

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#309]
Kliknięcie takiego przycisku powodowałoby wyświetlanie komunikatu o tym, że opcja możliwa tylko dla zalogowanych.

https://4programmers.net/Forum/Coyote/284617-komentarze_dla_gosci_pro_tip

**Comment by silvuss** [comment]
@adam-boduch Czy anonimowi użytkownicy mogą w ogóle jeszcze pisać gdziekolwiek na 4p?

**Comment by adam-boduch** [comment]
Tak, w komentarzach do ofert pracy. 

To zadanie jednak zostalo utworzone kiedy jeszcze mogli pisac na forum i mialo zachecic do logowania :) 

W tym zadaniu chodzi jednak o pozostawienie tego przycisku widocznego aby zachecic do rejestracji.
