### ISSUE TITLE
Za duże odstępy pomiędzy liniami kodu w znacznikach

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#310]
Temat znów powraca, bo już kiedyś wnioskowałem o zwężenie linii w znacznikach dla kodu. No i znów o to wnioskuję, albowiem odstępy pomiędzy liniami są zbyt duże i kod niepotrzebnie rozciągany jest w pionie. Porównałem odstępy z tym co widzę na co dzień w edytorze (przy standardowych ustawieniach, bez dodatkowych odstępów pomiędzy znakami i liniami) i z moich obliczeń wynika, że kod zajmuje o **10%** za dużo miejsca w pionie.

Poniżej zrzut ekranu z trzema kodami - po lewej oryginał (`line-height: 1.43`), w środku moja sugestia (`line-height: 1.25`), a z prawej zrzut z edytora kodu:

![code](https://cloud.githubusercontent.com/assets/8170730/23132062/a82f5782-f78c-11e6-90c0-3c8d1ff30aca.png)

Jak widać ustawienie `line-height` na `1.25` sprawi, że rozmiar kodu będzie bardzo bliski oryginałowi.

Nie pamiętam jak było to w poprzedniej wersji serwisu (po zmianie wysokości linii) - coś koło tego co proponuję, dlatego że też porównywałem kod z forum z kodem z **Lazarusa**. Według mnie zwężenie linii jest konieczne - kod będzie zajmować mniej miejsca, jego analiza będzie łatwiejsza, a puste linie w kodzie nie będą wybijać tak dużych dziur jak to widać na zrzutach.

**Comment by adam-boduch** [comment]
Zamykam w związku z ankietą: https://4programmers.net/Forum/Coyote/285129-czy_listingi_kodu_posiadaja_zbyt_duze_odstepy

**Comment by furious-programming** [comment]
I co teraz? Zainteresowanie ankietą praktycznie żadne... `:)`
