### ISSUE TITLE
Parsowanie strony przez facebook'a

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#311]
Przy wklejaniu linku na messengerze do strony głównej - fb parsuje wpisy z mikrobloga. Aby uniknąć takiej sytuacji można dać specjalne tagi (bodajże OG:....) dzieki czemu będziemy mogli ładnie udostępniać link do forum.
![zrzut ekranu 2017-02-21 o 17 58 19](https://cloud.githubusercontent.com/assets/5124712/23175445/ae2dced8-f85f-11e6-8206-176127400744.png)

**Comment by Lexonouri** [comment]
Jestem w trakcie przygotowywania poprawki
