### ISSUE TITLE
Błędne parsowanie linków

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#317]
https://4programmers.net/Forum/Off-Topic/285132-fotel_dla_programisty?p=1336165#id1336165 w poście dałem link do takiej strony
https://www.ergoexpert.pl/pl/p7386-fotel_wau_2_bialo-czarny_-_18_kolorow_(tkanina_bl)_.html

Został sparsowany do połowy.
![zrzut ekranu 27](https://cloud.githubusercontent.com/assets/5124712/23315635/5ef9a962-fac7-11e6-8422-0664a5be653e.png)

**Comment by adam-boduch** [comment]
poki co, obejscie tego problemu to zastosowanie skladnii markdown:

`<https://www.ergoexpert.pl/pl/p7386-fotel_wau_2_bialo-czarny_-_18_kolorow_(tkanina_bl)_.html>`

**Comment by Lexonouri** [comment]
To wyrażenie łyka ten link:
^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_()\+.~#?&\/\/=]*)$
