### ISSUE TITLE
Client-side syntax coloring

### ISSUE THREAD

**Issue by hauleth** [adam-boduch/coyote#323]
Do wyboru:

- https://highlightjs.org
- http://prismjs.com/index.html

**Comment by adam-boduch** [comment]
Geshi sprawia problemy? :) 
Masz racje: predzej czy pozniej trzeba bedzie go wywalic.

**Comment by hauleth** [comment]
Ano stara wersja nie wspiera wielu nowych języków, jako ostatnio sprawdzałem to nie było wsparcia ani dla Elixira ani dla Rusta.
