### ISSUE TITLE
`kbd` psuje inne znaczniki

### ISSUE THREAD

**Issue by twono** [adam-boduch/coyote#330]
Jeśli `kbd` jest pierwszym znacznikiem w linii (spacje są ignorowane) i potem w tej samej linii mamy dowolny tekst, to późniejsze znaczniki w poście przestają działać.

`Cokolwiek <kbd>D</kbd> ta linia nie psuje późniejszych znaczników`

`<kbd>C</kbd> a ta psuje`

**Comment by adam-boduch** [comment]
Dzięki za zgłoszenie. Niestety nie jest to błąd Coyote, ale biblioteki do parsowania markdown. Błąd został już zgłoszony. Niestety to nie pierwszy bug w tej bibliotece więc chyba trzeba będzie się jej pozbyć :/
