### ISSUE TITLE
Dziwne powiadomienia (powinny być do innych użytkowników)

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#338]
Od ~wczoraj(?) dostaję powiadomienia/notyfikacje o aktywnościach, które nie powinny być do mnie adresowane (np. "x docenił twój post w temacie y", gdy ja w tym temacie nigdy nie pisałem). Zwiększa się counter przy dzwoneczku/kopercie, ale gdy go rozwijam to znika. Postaram się wrzucić screeny.

**Comment by adam-boduch** [comment]
Czy teraz jest ok, czy nadal źle?

**Comment by KrzaQ** [comment]
Chyba jest ok - nie widziałem aby się powtarzało od pewnego czasu.

**Comment by adam-boduch** [comment]
Jakby się powtórzyło, to daj znać, a otworzymy ponownie to zadanie.

**Comment by KrzaQ** [comment]
Znów się powtarza problem. Co ciekawe widziałem dziś kilka razy powiadomienie po tym, że sam dodałem post lub komuś dałem łapkę w górę.

**Comment by KrzaQ** [comment]
I znów:
![](http://i.imgur.com/KmzaEfm.png)

**Comment by adam-boduch** [comment]
Poki co problem nierozwiazany. Wiecej info tutaj: https://4programmers.net/Forum/1347612

**Comment by KrzaQ** [comment]
W tym momencie dostaję powiadomienia, które powinna dostawać katelx. kq i katelx zaczynają się na k, może to jakiś trop?

**Comment by adam-boduch** [comment]
Heh, to chyba zbieg okoliczności :)

**Comment by KrzaQ** [comment]
Ciekawa sprawa, teraz dostałem powiadomienie zawierające część treści wiadomości prywatnej. Nad ikonką koperty pojawiła się jedynka, po rozwinięciu oczywiście żadnych nowych wiadomości nie było.

Może problemem są jednoczesne wielokrotne sesje z różnych przeglądarek/ip/komputerów?

**Comment by adam-boduch** [comment]
Zdaje się że już jest ok po wycofaniu zmian z serwera web socket.
