### ISSUE TITLE
Niepotrzebne przyciski pod postami w zamkniętych wątkach

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#340]
Jeśli wątek jest zablokowany (bo np. znajduje się w kategorii **Kosz** czy **Perełki**) to pod postami nie powinno być przycisków:

- **Obserwuj** - obserwacja nie ma sensu, bo w wątku i tak nic się nie zmieni,
- **Raportuj** - skoro wątek został przeniesiony do kategorii zamkniętej to moderacja na pewno zapoznała się z jego treścią i naniosła ewentualne poprawki.

Te przyciski można też usunąć z zamkniętych wątków, znajdujących się w otwartych kategoriach.

**Comment by silvuss** [comment]
Nie zgadzam się. Funkcja raportowania to rzeczywiście działanie zależne wyłącznie od bieżącego kontekstu, i w takiej sytuacji nie ma sensu. Ale funkcja obserwowania to działanie, które może być też rozpatrywane w kontekście przyszłym: teraz kliknę `Obserwuj`, a jak wątek zostanie kiedyś z jakiegokolwiek powodu przeniesiony do zwykłego działu (=odblokowany), to będę od razu to wiedzieć – będę obserwować wszystkie zmiany.
