### ISSUE TITLE
Black list

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#341]
Dobrze by było gdyby na forum istniała możliwość dodawania użytkowników do czarnej listy. Lista ta miałaby zastosowanie przy prywatnych wiadomościach.

Przypadek:
1. Użytkownik X pomaga użytkownikowi Y w prostym problemie
2. X wymienia z Y kilka PW
3. Użytkownik Y wykazuje się rażącą niewiedzą i co jakiś czas wysyła głupie pytania do X typu "A jak sprawdzić który element tablicy jest ostatni?"

Czynności:
1. Użytkownik X dodaje użytkownika Y do czarnej listy
2. Użytkownik Y nie może wysyłać PW do X, otrzymując komunikat "Zostałeś zablokowany"
3. Użytkownik X nie jest widoczny na liście potencjalnych odbiorców przy tworzeniu wiadomości przez Y.

Jedyny minus - nic nie powstrzyma użytkownika Y przed założeniem nowego konta i dalszego spamowania/pisania głupot/zadawania głupich pytań zamiast poszukać w google.

**Comment by furious-programming** [comment]
Drugi minus dotyczy wykorzystania wiadomości prywatnych do komunikacji związanej ze zleceniami. Jeśli zleceniodawca nie będzie zadowolony z wykonanej pracy, a zleceniobiorca doda go do czarnej listy, to jedyna możliwości kontaktu przepadnie.

Dodatkowo, nie powinno być możliwości dodania do czarnej listy moderatora lub administratora. Ta grupa użytkowników musi mieć możliwość kontaktu z każdym zarejestrowanym użytkownikiem serwisu.
