### ISSUE TITLE
Automatyczne dostosowywanie szerokości kolumn w tabelkach

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#347]
Póki co, kolumny w tabelkach posiadają taką samą procentową szerokość, bez względu na zawartość komórek. Przydało by się, aby szerokość kolumn była dostosowywana do ich zawartości - czyli tak jak było wcześniej.

Przykładowy post z tabelką - [Kasowanie wyrażeń bez liczby SQL](https://4programmers.net/Forum/1351764). Pierwsza kolumna powinna być bardzo wąska, tymczasem zajmuje połowę szerokości całej tableki.

**Comment by adam-boduch** [comment]
Hmmm, patrze w style i nie widze, zeby szerokosc kolumn byla ustawiona "na sztywno".

**Comment by furious-programming** [comment]
Ale przyznasz, że szerokość kolumn nie jest dostosowywana do ich zawartości?

**Comment by adam-boduch** [comment]
Nie wiem czemu w taki sposob przeglada je renderuje.
