### ISSUE TITLE
Dziwne sortowanie nicków zalogowanych użytkowników

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#350]
Przykładowa lista zalogowanych użytkowników (na głównej stronie forum) wygląda tak:

![list](https://cloud.githubusercontent.com/assets/8170730/25749381/9acd50c4-31ae-11e7-951a-5214bf6c5ccd.png)

Na pierwszy rzut oka nie widać, że lista ta dzieli się na dwie, posortowane alfabetycznie:

![groups](https://cloud.githubusercontent.com/assets/8170730/25749431/d463a284-31ae-11e7-8d78-961a84a1addc.png)

Tak samo wygląda to na głównej stronie serwisu. Nie wiem czy to bug czy feature, jednak podwójna lista trochę utrudnia odszukanie interesującego użytkownika.

**Comment by adam-boduch** [comment]
Widze, ze sortowanie dziala ok. Po prostu rozroznia male/wielkie litery.
