### ISSUE TITLE
Brak aktywowania pola do podania hasła w PA

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#351]
Po kliknięciu w pozycję **Panel administracyjny** w menu, przekierowuje moda/admina na stronę logowania. Po załadowaniu strony, pole edycyjne do wpisywania hasła nie zostaje aktywowane.

**Comment by adam-boduch** [comment]
Pole posiada atrybut `autofocus`. Byc moze nie jest obslugiwane w Twojej wersji przegladarki.
