### ISSUE TITLE
Wyróżnianie nicków moderatorów/administratorów podczas uzupełniania nicku

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#352]
**@olesio** zasugerował taki mały feature - po wpisaniu znaku `@` i wpisaniu kilku znaków, pojawia się okienko z listą sugerowanych nicków. Fajnie by było, gdyby w jakiś sposób wyróżnić moderatorów i administratorów.

Moja propozycja - jeśli dany prefiks użytkownika (czyli to co mamy już wpisane) pasuje do nazwy któregoś z moderatorów czy administratorów, to najpierw wyświetlić listę użytkowników specjalnych<sup>1</sup>, a po poziomym separatorze wyświetlić pozostałych. Przy czym fajnie by było, gdyby obok nazwy moda/admina, np. w nawiasach podać funkcję pełnioną na forum (czyli to co ma ustawione jako grupa użytkownika).

**1.** Użytkownik specjalny to taki, który ma wybraną dodatkową grupę, czyli np. administrator, moderator, partnerzy itd.

**Comment by adam-boduch** [comment]
Spokojnie można wyświetlać grupę użytkownika obok nazwy użytkownika, to jest dość proste w implementacji.
