### ISSUE TITLE
nie mogę zmienić avatara (upload photo)

### ISSUE THREAD

**Issue by bonsoftpl** [adam-boduch/coyote#357]
Wszedłem sobie w mój profil, moje konto, start i na zdjęciu mam link [Zmień](https://4programmers.net/index.php/User/Photo/Upload).  Klikam go, ale wyrzuca błąd 404. Możecie naprawić?

Jestem tu nowy i tak przy okazji napiszę, że fajne forum. Wiedza ludzi robi wrażenie, oceniam po forum Java.

**Comment by adam-boduch** [comment]
Problemem jest `index.php` w adresie. Proszę wejść pod URL z pominięciem `index.php`: https://4programmers.net/User My tymczasem przygotujemy poprakwę, która zadba o "wycięcie" `index.php` z adresu :)
