### ISSUE TITLE
h1 w markdown nie działa (?)

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#358]
post: https://4programmers.net/Forum/1365292

```
Oryginalny post
===
```
Zamieniane jest na `<h1>Oryginalny post</h1>` - z `<>` wyescapowanymi. Tj. widać znaczniki, zamiast ich efektu:
![](http://i.imgur.com/8ZeHIJP.png)

**Comment by adam-boduch** [comment]
Hmm, czyli z tego wynika, ze markdown zadzialal, ale parser HTML wycial ten znacznik. Pewnie nie jest doadny do listy dozwolonych znacznikow. Sprawdze.
