### ISSUE TITLE
Funkcjonalność pastebin

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#359]
Nie wiem czy do wrzucania kodu do pastebina 4p - należy spełniać jakieś dodatkowe warunki. Ale chyba natknąłem się na błąd. W polu nazwa domyślnie jest mój nick, i nawet pomimo jego zmiany - zapisany zostaje nick. Podobnie z czasem wygaśnięcia-zaznaczyłem "nigdy" - ustawiła się opcja 72h. Mysłałem że może źle coś kliknąłem - ale przy drugiej próbie błąd pojawił się ponownie.

https://4programmers.net/Pastebin/6841 - miało być `nigdy` z nazwą `funkcje_dla_przykladu`

https://4programmers.net/Pastebin/6842 - tu kolejna próba (ten wpis można usunąć(a ten powyżej powinien zostać)

**Comment by adam-boduch** [comment]
Pastebin nie mozna edytowac. 

Po wejsciu na dowolny wpis w formularzu ponownie pojawiaja sie domyslne wartosci - tj. login uzytkownika oraz opcja wygasniecia. Klikniecie przycisku "Zapisz" spowoduje dodanie nowego wpisu. Twoj wpis na pewno dodal sie z prawidlowymi ustawieniami. Po wejsciu w niego, mozesz natomiast dodac nowy - z nowymi ustawieniami/nazwa.

Tak wiec nie jest to bug. Coz, moze rzeczywiscie jest to malo intyuicyjne.
