### ISSUE TITLE
Błędne przekierowania przy starym(?) linku

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#360]
Nie umiem lepiej zdiagnozować.

https://4programmers.net/Forum/Spolecznosc/Perelki/265368-pilne_kolos_z_struktur - The page isn’t redirecting properly
https://4programmers.net/Forum/Spolecznosc/Pere%C5%82ki/265368-pilne_kolos_z_struktur - link działa ok

**Comment by adam-boduch** [comment]
Naprawiłem przekierowania.

Zmiana adresu działu Perełki raczej nie był celowym działaniem :/ Pewnie stało się to podczas migracji na nową wersję Coyote, w zeszłym roku. Nikt do tej pory się nie zorientował.
