### ISSUE TITLE
Brak paginacji u góry na stronie własnych mikroblogów

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#361]
Na **[głównej stronie mikroblogów](https://4programmers.net/Mikroblogi)**, paginacja znajduje się nad pierwszym wpisem na stronie, a także pod ostatnim wpisem. Jednak na stronie **[własnych mikroblogów](https://4programmers.net/Profile/1/Microblog)**, paginacja znajduje się wyłącznie pod ostatnim wpisem - tej u góry brakuje.

**Comment by silvuss** [comment]
Nie widzę różnicy. @adam-boduch Czy zostało to już zmienione?
