### ISSUE TITLE
Zbędna ikonka do doceniania własnych postów

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#362]
Dla zalogowanego użytkownika opcja doceniania własnych postów nie jest dostępna, więc łapka do plusowania nie powinna być w takich przypadkach wyświetlana.

**Comment by Danon** [comment]
Trochę dziwnie by to wyglądało. Teraz ta ikonka oprócz funkcji głosowania, pełni też funkcję wizualną: ikonka sugerująca że ta liczba to głosy.

Może dodać wtedy inną ikonkę symbolizującą głosy?

**Comment by adam-boduch** [comment]
Zgadzam się z @Danon

**Comment by silvuss** [comment]
Niedawno napisałem na forum post dot. tego problemu, nie wiedząc o zgłoszeniu; linkuję więc: https://4programmers.net/Forum/Coyote/336122-wylaczenie_przyciskow_polubienia_przy_wlasnych_wpisach_na_mikroblogu_oraz_postach_na_forum
