### ISSUE TITLE
Parsowanie markdown - myślniki

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#368]
Przy wpisaniu kilku myślników tak jak w poście https://4programmers.net/Forum/1377981
tekst staje się większy - wg mnie chyba niepotrzebnie / błędnie.

![zrzut ekranu 2017-07-06 o 18 23 42](https://user-images.githubusercontent.com/5124712/27921563-73585aca-6278-11e7-9f07-918c231fe085.png)

**Comment by adam-boduch** [comment]
Taka jest specyfikacja markdown. To nie jest blad, ale celowe dzialanie. W ten sposob tworzymy naglowki.
