### ISSUE TITLE
Niekompletne oznaczanie kategorii jako przeczytanej

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#369]
Jeśli w danej kategorii znajdują się wątki z nieprzeczytanymi postami, to w widoku kategorii, obok jej nazwy, widnieje ikonka kartki z pomarańczowymi liniami, którą da się kliknąć. W prawej kolumnie widnieje tytuł najświeższego wątku z nieprzeczytanymi postami. Przykład niżej:

![0](https://user-images.githubusercontent.com/8170730/28082944-3784d6f4-6674-11e7-9605-33f40ba1197a.png)

Aby oznaczyć całą kategorię jako przeczytaną, należy kliknąć w ikonkę kartki – w tę z lewej strony:

![1](https://user-images.githubusercontent.com/8170730/28082971-479ef4ac-6674-11e7-8e69-9a6a180d9364.png)

Po kliknięciu w nią, zmienia się na ikonkę z zielonymi liniami i już nie da się drugi raz w nią kliknąć (prawidłowo). Jednak zielona, mała ikonka kartki w prawej kolumnie, nie zmienia się na białą:

![2](https://user-images.githubusercontent.com/8170730/28083021-6bee3db8-6674-11e7-8368-6d25bef03ff7.png)

**Comment by silvuss** [comment]
@adam-boduch Czy po ostatnich zmianach w tym zakresie ten problem został rozwiązany, czy nie?

**Comment by adam-boduch** [comment]
Tak :)
