### ISSUE TITLE
Dodanie potwierdzenia chęci zablokowania wątku

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#375]
Póki co, kliknięcie w przycisk blokowania wątku wykonuje jego blokowanie bez potwierdzenia – przyda się takie potwierdzenie dodać. Jest to chyba jedyna opcja w serwisie, która potwierdzenia nie wymaga, a modyfikuje zawartość.

Poza tym, łatwo niechcący zablokować wątek, nie trafiając w przycisk do zmiany tytułu wątku (co zdarza mi się notorycznie, przy natłoku wątków do poprawienia).

**Comment by adam-boduch** [comment]
W ten sposob mozemy szybko blokowac/odblokowywac watkoi, bez przeladowania strony. Nie sadze zeby trzeba bylo to wprowadzac. W razie pomylki drugi klik i juz odblokowane ;)
