### ISSUE TITLE
Logowanie poprez OAuth: obsluzyc akcje anulowania

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#382]
Jezeli user podczas logowania podczas OAuth, zmieni zdanie i nacisnie przycisk "Anuluj", to jest cofany do naszego serwisu gdzie wyrzucany jest wyjatek.

**Comment by wlisik** [comment]
a tak nie powinno być?

**Comment by adam-boduch** [comment]
W takim przypadku użytkownik powinien być przekierowany z powrotem do formularza logowania. Obecnie zamiast tego widzi stronę błędu: "Ooops something went wrong".
