### ISSUE TITLE
Możliwość oceniania postów w zablokowanych działach

### ISSUE THREAD

**Issue by Marooned-MB** [adam-boduch/coyote#401]
Wątki w zablokowanych działach (np. Perełki) mają wyłączoną możliwość dodania +1 do postu. Moim zdaniem nie ma do tego podstaw. Jeśli są, to w takim razie sugerowałbym schowanie ikony kciuka.

**Comment by adam-boduch** [comment]
W zablokowanych wątkach/kategoriach zabronione są wszelkie akcje. Wyjątkiem jest możliwość dodawania postów przez moderatorów lub ich edycji.

Ikona kciuka jest wyświetlona, ale po kliknięciu wyświetlany jest ładny komunikat wyjaśniający dlaczego głos nie został oddany w tym akurat dziale/wątku.

IMHO nie ma potrzeby zmiany w tej funkcjonalności póki co (nikt się nie skarży :))
