### ISSUE TITLE
Dodanie powiadomień o komentarzu we wpisie na blogu

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#402]
Chodzi o dodanie powiadomień w nowych komentarzach pod cudzym wpisem na blogu, jeśli ten wpis obserwujemy i/lub jeśli sami też go skomentowaliśmy.

Dzięki temu nie trzeba będzie za każdym razem podawać `@nicku` użytkownika podczas pisania komentarza, aby go przywołać (bo jak się go nie przywoła, to nie będzie wiedział, że ktoś coś napisał).

Taka opcja już istnieje, jednak dotyczy wyłącznie postów na forum.

**Comment by adam-boduch** [comment]
Mozna rowniez obserwowac dane wpisy na mikroblogu.

**Comment by furious-programming** [comment]
Tak, tyle że jeśli obserwacja wpisu na blogu nie powoduje rozsyłania powiadomień o nowych komentarzach, jeśli w tych komentarzach nie występuje nasz nick poprzedzony małpką.

**Comment by adam-boduch** [comment]
Moze masz wylaczone jakies powiadomienia w ustawieniach? to powinno zadzialac.

mozemy przetestowac: https://dev.4programmers.info/Mikroblogi/View/41#entry-41
