### ISSUE TITLE
Usunięcie wpisu nie aktualizuje licznika reputacji

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#422]
Po usunięciu postu z działu technicznego lub wpisu na blogu, reputacja użytkownika (autora postu/wpisu) nie jest aktualizowana. Przyznane punkty reputacji za usunięty post/wpis powinny być cofane.

**Comment by adam-boduch** [comment]
Na pewno usuniecie wpisu z mikrobloga, cofa punkty przyznane za utworzenie wpisu. Nie cofa natomiast punktow przyznanych w ramach przyznanych ocen. To jest akurat celowe dzialanie, gdyz ktos jednak ten wpis przed usunieciem docenil (i nie byl to autor) jako wartosciowy.

**Comment by furious-programming** [comment]
Zgadzam się, jednak posiadanie punktów za treści już nieistniejące w serwisie jest raczej bezcelowe. W ten sposób można mieć konkretną liczbę punktów reputacji (dowolnie dużą) i jednocześnie nie posiadać żadnego swojego wpisu w serwisie. Reputacja widmo – punkty są, ale nie wiadomo za co i nikt się tego nie dowie.
