### ISSUE TITLE
Soft delete załączników na mikroblogu

### ISSUE THREAD

**Issue by furious-programming** [adam-boduch/coyote#424]
Jeśli do załączników wpisu na blogu dodamy załącznik obrazkowy i opublikujemy wpis, a następnie wejdziemy do jego edycji i usuniemy załącznik (klikając w jego miniaturkę), to obrazek zostanie usunięty z wpisu, a nie z serwera.

Stary adres w domenie `https://static.4programmers.net/uploads/attachment/*` w dalszym ciągu prowadzić będzie do istniejącego pliku.

**Comment by furious-programming** [comment]
**Aktualizacja**

Dodane do wpisów obrazki nie są od razu usuwane po usunięciu załączników w trakcie edycji wpisu, ale ogólnie usuwane są – po pewnym czasie (nie wiem dokładnie po jakim). Bądź co bądź, to zgłoszenie jest nieaktualne – poprawki pod tym kątem nie są wymagane.

**Comment by silvuss** [comment]
@furious-programming to Ty nie masz możliwości zamknięcia tutaj?
