### ISSUE TITLE
Powiadomienie, które prowadzi do nieistniejącej odpowiedzi

### ISSUE THREAD

**Issue by xhexe** [adam-boduch/coyote#436]
Zaobserwowałem już jakiś czas temu problem z powiadomieniami prowadzącymi do nieistniejących komentarzy/odpowiedzi. 
Mianowicie otrzymuję powiadomienie, które jest widoczne na liście. Natomiast po kliknięciu w nie, i przejściu do wątku - nie widać tej aktywności. Nie jest to jednorazowy przypadek i pojawia się "co jakiś czas".
Pytanie czy problem jest czysto techniczny czy też ludzie dodają odpowiedź/komentarz, a następnie ją usuwają, a powiadomienie pozostaje?

**Comment by adam-boduch** [comment]
Prawdopodobnie te posty/komentarze są usuwane przez autorów albo moderatorów.
