### ISSUE TITLE
Rozjechanie się zawartości "Popularne wpisy na blogu"

### ISSUE THREAD

**Issue by Barto-Paja** [adam-boduch/coyote#441]
Tekst z treścią nie mieści się w założonej szerokości.

Przeglądarka: Brave

![przechwytywanie](https://user-images.githubusercontent.com/24964850/52476766-ffa04a00-2b9f-11e9-9946-844978028cc9.JPG)

**Comment by adam-boduch** [comment]
https://4programmers.net/Forum/1318110

Już kiedyś mieliśmy podobny problem. Stosujemy style zaproponowane przez @Marooned-MB w w/w poście. Nie mam pomysłu jak to "ulepszyć".

U mnie na chrome jest ok.

**Comment by Marooned-MB** [comment]
Dyskusja i proponowane rozwiązanie
https://4programmers.net/Forum/Coyote/322550-rozjezdzanie_sie_wpisu_na_mikroblogu?p=1567330#id1567330

**Comment by adam-boduch** [comment]
Poprawione
