### ISSUE TITLE
Rozjechana pozycja avatara i nazwy użytkownika po dodaniu komentarza z grafiką do wpisu z mikrobloga

### ISSUE THREAD

**Issue by olekstomek** [adam-boduch/coyote#454]
Wydaje się, że położenie między sobą avatara i nazwy użytkownika po wstawieniu komentarza z grafiką do wpisu mikrobloga jest "rozjechane".
![image](https://user-images.githubusercontent.com/26818304/59093965-6991eb80-8915-11e9-9779-644e28a2012f.png)

**Comment by DorianMazur** [comment]
@olekstomek Mógłbyś podać link do tego wpisu?

**Comment by olekstomek** [comment]
> @olekstomek Mógłbyś podać link do tego wpisu?

@DorianMazur link do tego komentarza: https://4programmers.net/Mikroblogi/View/49458#comment-49463
W widoku mobile (Chrome na Androidzie) nie ma takiego problemu.

**Comment by DorianMazur** [comment]
Naprawione - #455
