### ISSUE TITLE
Brak połączenia z bazą danych

### ISSUE THREAD

**Issue by DorianMazur** [adam-boduch/coyote#457]
Próbowałem postawić testowy serwer, wszystko szło dobrze aż do czasu.
Nie mogę nawiązać połączenia z bazą, mimo iż postgresql jest zainstalowany, baza coyotee stworzona a w pliku .env jest odpowiednia konfiguracja:

DB_HOST=db (próbowałem też localhost)
DB_DATABASE=coyotee
DB_USERNAME=postgres
DB_PASSWORD=

```
In Connection.php line 664:

  SQLSTATE[08006] [7] FATAL:  database "coyotee" does not exist (SQL: select * from information_schema.tables where table_schema = public and t
  able_name = migrations)


In PDOConnection.php line 31:

  SQLSTATE[08006] [7] FATAL:  database "coyotee" does not exist


In PDOConnection.php line 27:

  SQLSTATE[08006] [7] FATAL:  database "coyotee" does not exist

```

Serwer: http://35.232.241.159:8880/

**Comment by DorianMazur** [comment]
Po kilku reinstalacjach i tworzeniu baz danych w kółko na nowo zadziałało. Nie wiem co było problemem, ale testowałem bazę z innymi programami i tylko coyote jej nie widział.

**Comment by adam-boduch** [comment]
Polecam uzyc dockera (instrukcja znajduje sie w pliku `README`)

**Comment by DorianMazur** [comment]
Użyłem właśnie dockera.

**Comment by adam-boduch** [comment]
Docker tworzy bazę danych o nazwie `coyote` a tymczasem Ty w konfiguracji miales `coyotee`.

**Comment by DorianMazur** [comment]
Próbowałem coyote, potem sam stworzyłem bazę i próbowałem z coyotee. To i to nie działało.

**Comment by DorianMazur** [comment]
Przeinstalowałem i wtedy zaskoczyła domyślna baza o nazwie `postgres`
