### ISSUE TITLE
Komunikat dotyczący hasła w różnych miejscach w formularzu logowania, oznaczony nieprawidłowy błędny input

### ISSUE THREAD

**Issue by olekstomek** [adam-boduch/coyote#459]
Tak jak na zrzutach ekranu - brak spójności wyświetlania się komunikatów dotyczących hasła.
Komunikat, że wymagane jest hasło pojawia się w prawidłowym miejscu i zaznaczony jest input do wprowadzania hasła
![4p_wymagane_hasło](https://user-images.githubusercontent.com/26818304/61528347-ce655900-aa1e-11e9-8067-00504fbeecec.PNG)
 z kolei jeśli podam błędne hasło to komunikat o błędnym haśle pojawia się w miejscu gdzie pojawia się ewentualny komunikat dotyczący nieprawidłowości z np nazwą użytkownika, dodatkowo zaznaczony jest na czerwono input nazwa użytkownika zamiast input z hasłem. 
![4p_nieprawidłowe_hasło](https://user-images.githubusercontent.com/26818304/61528353-d0c7b300-aa1e-11e9-83ac-96ffac486267.PNG)

**Comment by msnowak** [comment]
Sugestia,
nie wypadałoby tego przedstawiania błędów przeprojektować aby nie pokazywała się informacja o tym czy błędny jest login czy hasło? Poza limitem logowań na pewno dobrą praktyką jest nie wskazywanie, że dany user istnieje, ale nie znamy jego hasła :)
