### ISSUE TITLE
Możliwość utworzenia shortlinka do tematu na podstawie danych z api/topics

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#479]
Shortlinki są w formacie `https://4programmers.net/Forum/<post_id>`. Aby można było tworzyć takie do tematów (a raczej do pierwszego postu w temacie), potrzebne jest jedno z poniższych
- pozycja `first_post_id` albo zbliżona, zawierająca id pierwszego posta
- pozycja `short_url` zawierająca już skrócony URL
- możliwość wyszukiwania postów po temacie w api/posts (na razie chyba się nie da)
- jakieś inne rozwiązanie

Bardzo proszę o dodanie tej możliwości! :)

**Comment by adam-boduch** [comment]
Dodałem pola `first_post_id` oraz `last_post_id`. Jest już na gh.
