### ISSUE TITLE
Treść popularnego wpisu w mikroblogu nie pokazuje się w zakładce "Popularne wpisy"

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#490]
Treść tego posta na mikroblogu nie pokazuje się w `Popularne wpisy`
https://4programmers.net/Mikroblogi/View/64095#entry-64095

![image](https://user-images.githubusercontent.com/6136794/73595984-625fc380-451e-11ea-90d9-63e604564c86.png)

**Comment by piatkiewicz** [comment]
Pewnie `excerpt` trzeba by opakować jeszcze w `htmlspecialchars()`
https://github.com/adam-boduch/coyote/blob/878b6259129482a408efcc8d09044ec08bd387a3/resources/views/microblog/home.twig#L79
