### ISSUE TITLE
Usuwanie nazwy użytkownika gdy zakończone jest znakiem unicode

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#497]
https://4programmers.net/Forum/Coyote/336185-wzmianka_uzytkownika_przez_znak_at_zakonczona_wielokropkiem_nie_wyswietla_sie

**Comment by Dzidzileyla** [comment]
Hej @adam-boduch,

Pytanie do ostatniego posta w tym topic'u.

Jaki inny lib proponujesz zamiast ParseDown?

**Comment by adam-boduch** [comment]
https://github.com/thephpleague/commonmark
