### ISSUE TITLE
Niepoprawna wartość ostatnio widzianego

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#502]
Przykład:  https://4programmers.net/Forum/1657471
![image](https://user-images.githubusercontent.com/1174663/75485236-a2458980-59aa-11ea-81e8-534da66bda96.png)

Post dodany 2 minuty temu, ostatnio widziany 15 minut temu. Podobny przypadek wydarzył mi się gdy odpowiedziałem w istniejącym temacie kilka dni temu.

**Comment by adam-boduch** [comment]
Zostało to naprawione przy okazji innego błędu.

**Comment by KrzaQ** [comment]
https://4programmers.net/Forum/C_i_C++/339875-stoper?p=1677404#id1677404 Błąd występuje ponownie

![](https://i.imgur.com/hAvYXUt.png)
