### ISSUE TITLE
Podpowiedź do uzupełniania nicka powinna priorytetyzować te wypowiadające się w dyskusji

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#503]
W tym przypadku usera nie ma na liście, a dodanie spacji usuwa podpowiedzi.
![](https://i.imgur.com/xbabqLv.png)

URL: https://4programmers.net/Forum/C_i_C++/337009-c_liczby_polpierwsze?p=1658517

**Comment by adam-boduch** [comment]
Tak to właśnie działa. Nie wiem tylko czemu w tym konkretnym przypadku nie zadziałało. Nie mogę coś odwzorować tego konkretnego przykładu :(

**Comment by KrzaQ** [comment]
Ten user miał spację w nazwie - podejrzewam, że to to?

**Comment by adam-boduch** [comment]
Niekoniecznie. Moj login tez ma spacje w nazwie a dziala. Mozesz sprawdzic tutaj: https://4programmers.net/Forum/Coyote/337383-redesign_listy_watkow_w_kategorii?p=1663736#id1663736

**Comment by KrzaQ** [comment]
Jesteś pierwszy na liście (ten z wątku teraz też jest).

**Comment by adam-boduch** [comment]
Hmmm, to dziwne, bo wydaje mi sie ze nic nie naprawialem w zwiazku z tym. Ale wazne ze dziala ;)
