### ISSUE TITLE
Wpisy zawierające escapowane encje/tagiHTML nie są wyświetlane poprawnie w części "Popularne wpisy"

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#510]
Niektóre posty zawierające tagi HTML lub inne dziwne znaczki (np. apostrofy) nie są poprawnie wyświetlane w części "Popularne wpisy"

Podejrzewam, że to może być problem po fixie #490 ale nie piszę w PHP więc nie mam pewności

Posty ze screena:
https://4programmers.net/Mikroblogi/View/66665
https://4programmers.net/Mikroblogi/View/66652

![image](https://user-images.githubusercontent.com/6136794/76969323-88082700-692a-11ea-83cc-539d73310b7f.png)

**Comment by adam-boduch** [comment]
Tak, racja, musiałem wycofać ten commit
