### ISSUE TITLE
Nieczytelna czcionka w sekcji 'Ostatnia aky'

### ISSUE THREAD

**Issue by Encceladus** [adam-boduch/coyote#518]
W Google Chrome przy ustawieniu flagi dark mode na Enabled, czytelność tej sekcji jest niska.

![image](https://user-images.githubusercontent.com/58974297/79731264-5223dd00-82f2-11ea-84ae-dc184ad63da0.png)

**Comment by adam-boduch** [comment]
Wszystko przez `text-shadow` w CSS. Można będzie og usunąc.
