### ISSUE TITLE
Przycisk rozwinięcia (czegoś) w prywatnych wiadomościach nic nie robi

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#522]
Nie jestem pewien do czego jest ten przycisk ale nie ma opisu ani nic nie rozwija, więc wydaje mi się że to błąd lub jakaś pozostałość po czym co kiedyś istniało

![image](https://user-images.githubusercontent.com/6136794/79924366-e64b8c80-8437-11ea-918a-300a586a53f2.png)

**Comment by adam-boduch** [comment]
ikona powinna rozwijać listę jezykow
