### ISSUE TITLE
Brak powiadomienia o nowym komentarzu

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#538]
Nie dostałem powiadomienia o komentarzu, czy powiązana z ostatnimi problemami:

![](https://i.imgur.com/X0tfEWc.png)

Wątek: https://4programmers.net/Forum/1677671

**Comment by adam-boduch** [comment]
Czy możliwe że powiadomienie zostało zgrupowane? Bo widzę dwa komentarze tej samej osoby.

**Comment by KrzaQ** [comment]
Nie widziałem nic co by sugerowało grupowanie. Byłem przy komputerze i nie zauważyłem też notyfikacji od przeglądarki. Ale możliwe, że zwyczajnie nie zauważyłem.

**Comment by adam-boduch** [comment]
Dwa lub kilka powiadomien jednego typu sa grupowane. Dopoki nie rozwiniesz okna powiadomien to kolejne powiadomienia tego typu beda grupowane.
