### ISSUE TITLE
Niewłaściwie formatowany tekst w komentarzu mikrobloga

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#540]
W moim komentarzu opisałem adnotację z PHP - `<<Example>>`, która nie różni się niczym od reszty tekstu (czyli nie wygląda jakby na to zostało nałożone jakieś specjalne formatowanie) ale wielka litera została zamieniona na małą literę - `<<example>>`

<img width="954" alt="Zrzut ekranu 2020-05-19 o 11 31 51" src="https://user-images.githubusercontent.com/6136794/82310240-6b3cae00-99c4-11ea-9ee7-de8e1ee49da5.png">
<img width="960" alt="Zrzut ekranu 2020-05-19 o 11 31 47" src="https://user-images.githubusercontent.com/6136794/82310242-6d067180-99c4-11ea-83b9-02e1d9224f1a.png">

Post na mikroblogu: https://4programmers.net/Mikroblogi/View/71655

**Comment by adam-boduch** [comment]
Prawdopodobnie zadziałał tutaj parser HTMLPurifier który uznał to za tag HTML. Należy użyć znaków \` aby uniknąć formatowania.

**Comment by KamilZielinski** [comment]
Wyjaśnione, w takim razie zamykam :)
