### ISSUE TITLE
Przejście "Wstecz" po przejściu przez kilka stron wyszukiwarki zwraca JSONa z ES zamiast strony z wynikami

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#545]
Tego błędu nie potrafię reprodukować za każdym razem. Chodzi o problem podczas powracania do poprzedniej strony w wynikach wyszukiwania, kiedy powrót z użyciem przycisku **Wstecz** (przyciskiem przeglądarki) powoduje wyświetlenie nam tylko JSONa pochodzącego z API/ElasticSearcha .

Kroki:
1. Użyj wyszukiwarki umieszczonej na górny pasku wyszukując dowolną frazę np. "elixir" i zatwierdź enterem
2. Przejdź do następnej strony z wynikami, a następnie wróć wstecz korzystając z przeglądarkowego przycisku "**Wstecz**" (nie poprzez użycie paginacji)
3. Powtórz kilka razy (np. przechodząc na inne strony, a następnie wróć do poprzedniej strony), ponieważ nie za każdym razem udaje się odtworzyć błąd

![jsones](https://user-images.githubusercontent.com/6136794/85951011-953ca500-b960-11ea-9e7f-82a124099008.png)

**Comment by adam-boduch** [comment]
Na jakiej przeglądarce to występuje?

**Comment by KamilZielinski** [comment]
Chome (MacOS) - Wersja 83.0.4103.116 (Oficjalna wersja) (64-bitowa). Na MacOS i Windows (mogę podać wersję po pracy) to samo

**Comment by KamilZielinski** [comment]
Windows, Chrome `Wersja 83.0.4103.116 (Oficjalna wersja) (64-bitowa)`
