### ISSUE TITLE
Brak możliwości przejścia na stronę >100 w wynikach wyszukiwania

### ISSUE THREAD

**Issue by KamilZielinski** [adam-boduch/coyote#560]
Chciałem poszukać jakichś wzmianek o Facebooku w przeszłości i dostałem 126 stron wyników, niestety nie można przejść na wyniki powyżej setnej strony.
https://4programmers.net/Search?q=facebook
Ręczne wejście na stronę https://4programmers.net/Search?q=facebook&page=101
 rzuca błędem  `The given data was invalid.`.

Jeśli to wynika z ograniczeń ES'a (kojarzę, że wydajność spada jeśli chcemy mieć większą ilość stron z wynikami), to może jest chociaż możliwość posortowania wyników wg daty? Wtedy nie musiałbym dobijać się do ostatniej strony z paginacji. Niestety to tylko częściowo rozwiąże problem bo przy >201 wynikach to znów przestanie działać bo nie dostaniemy się do 1 wyniku :/

**Comment by adam-boduch** [comment]
Hmm, musialoby istniec sortowanie w 2 kierunkach. Obecnie tylko sortujemy od najnowszego, bo w sumie kto by chcial (oprocz Ciebie :P) jakies stare wyniki ogladac ;)

**Comment by adam-boduch** [comment]
Limit zostal podniesiony do 1500 stron wyszukiwania
