### ISSUE TITLE
Overflow mikrobloga

### ISSUE THREAD

**Issue by grski** [adam-boduch/coyote#576]
![image](https://user-images.githubusercontent.com/16924479/97091118-a9a45c00-1639-11eb-91ea-659dbdd1f71a.png)

Może to tylko u mnie albo dla konkretnego wpisu.
Wpis: [Ostatnio sobie trochę klikam...](https://4programmers.net/Mikroblogi/View/85064)
Przeglądarka: najnowszy ff.
OS: Manjaro
Mam ublocka i privacy badgera, ale bez nich też nie działa.
Rozdziałka 2k.

**Comment by tomasz-michalski** [comment]
Potwierdzam, że błąd występuje też na Firefox 82.0 (najnowszy), Windows 10.

U mnie pomaga dodanie stylu `.media-body {min-width: 0;}`. W takiej sytuacji jednak obcięte zostają zbyt duże obrazki, co można poprawić np. dodając skalowanie poprzez `.media-body img {max-width: 100%;}`.

**Comment by adam-boduch** [comment]
Potwierdzam, ze to zadzialalo. Chociaz tak naprawde nie wiem dlaczego ... ;)
