### ISSUE TITLE
Ukrywanie wpisów wybranych osób

### ISSUE THREAD

**Issue by vpiotr** [adam-boduch/coyote#586]
Przy wybranej osobie (w profilu lub przy poście) można by dodać opcję ukrywania postów pochodzących z wybranego konta.
Taka funkcjonalność jest dostępna np. na LinkedIn (tam jest "Unfollow <user>" w miejscu obok "Report this post").

**Comment by adam-boduch** [comment]
Duplikat #446

**Comment by vpiotr** [comment]
Nie do końca duplikat, w #446  chodzi o mikrobloga, mi tutaj chodziło o cały portal (wątki i mikroblogi - posty i komentarze).

**Comment by adam-boduch** [comment]
Niestety na forum nie jest już to takie proste. Oto dlaczego: https://4programmers.net/Forum/Coyote/344849-blokowanie_postow_i_komentarzy_wybranego_uzytkownika?p=1714254#id1714254

**Comment by vpiotr** [comment]
@adam-boduch czyli zakładamy tylko zgłoszenia subiektywnie łatwe?
https://www.youtube.com/watch?v=DmEoC6Jt_PM

**Comment by adam-boduch** [comment]
Ależ skąd. Zawsze zachęcam do pull requestów jeżeli czujesz się na siłach :)
