### ISSUE TITLE
UX/UI: dodać focus po edycji komentarza

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#596]
Dotyczy:

- edycji komentarza na forum
- edycji komentarza na mikroblogach
- formularza przenoszenia wątków
- formularza usuwania postów

https://4programmers.net/Forum/Coyote/345824-wszedobylski_brak_fokusowania_kontrolek_glownie_pol_edycyjnych

**Comment by furious-programming** [comment]
Dotyczy też:

* edycji głównej treści wpisu na mikroblogach.

**Comment by adam-boduch** [comment]
Zrobilem globalnie dla kazdeog popupa (okna modal). ustawia sie focus na 1 elemencie select albo input.
