### ISSUE TITLE
Komponent edycji postu/mikroblogu wraz z edycją skrawków kodu

### ISSUE THREAD

**Issue by adam-boduch** [adam-boduch/coyote#602]
Więcej o pomyśle pisałem tutaj: https://4programmers.net/Forum/Coyote/346083-praca_z_kodem_w_formularzu_skrawki_kodu

**Comment by Danon** [comment]
Ja tylko dodam, że jak będzie nowy edytor to wyciąganie i update'owanie kodu w treści będzie bardzo proste.

**Comment by adam-boduch** [comment]
Przypisałem Ciebie do tego zadania bo myślę że jak go wdrożymy to będziemy mogli zamknąć to zgłoszenie. Wydaje mi się że edytor to nawet lepsze rozwiązanie niż ten mój pomysł z zakładkami ;)

**Comment by Danon** [comment]
Chyba tak.

Ale powiedz mi, Ty te zakładki, to miałeś na myśli taki prosty edytor jak np z przenoszeniem linii i indentami; czy miałeś też wzję  na np. rename zmiennych, etc.?

**Comment by Danon** [comment]
@adam-boduch Albo o jakich funkcjach myślałeś? Bo może niektóre z nich da się bardzo łatwo i szybko dodać?

**Comment by adam-boduch** [comment]
Tak, myślałem o textarea w głównej zakładce oraz prosty edytor kodu w pozostałych :) A teraz będziemy mieli 2 w 1 więc lepiej :)
