### ISSUE TITLE
Kliknięcie w obrazek załącznika usuwa go zamiast dodać do posta jako kod markdown

### ISSUE THREAD

**Issue by KrzaQ** [adam-boduch/coyote#610]
To jakiś nowy bug, bo jeszcze niedawno działało.
![](https://i.imgur.com/VJTg032l.png)

**Comment by adam-boduch** [comment]
Hmm, dodanie załacznika na forum powinno z automatu dodac go w tresci posta. Czy mowa tutaj o mikroblogach? Bo jezeli tak, to tu sie nic nie zmienilo.

**Comment by KrzaQ** [comment]
[link do posta][1]

Być może użytkowniczka usunęła, może jej nie dodało. W każdym razie nie ma już możliwości wkliknięcia załącznika aby to zrobić

[1]: https://4programmers.net/Forum/C_i_C++/347247-sumowanie_dzielnikow_w_zakresie_100_z?p=1731805#id1731805

**Comment by adam-boduch** [comment]
Cos wymyslimy ... :)
