### ISSUE TITLE
Czy wraz z usunięciem komentarza pod wpisem na mikroblogu wątek nadal powinien być obserwowany?

### ISSUE THREAD

**Issue by olekstomek** [adam-boduch/coyote#671]
Czy jest to zamierzone zachowanie? 
- dodaj jeden komentarz to wpisu na mikroblogu
- usuń dodany komentarz

Okazuje się że wątek jest jako obserwowany mimo braku komentarza pod wpisem. Czy wraz z usunięciem komentarza pod wpisem wątek nadal powinien być obserwowany (przy założeniu że jest/był to jedyny komentarz z danego konta pod wpisem)?

**Comment by Danon** [comment]
No tak to jest teraz zrobione.

Weź pod uwagę że nie tylko autor może skasować, ale też moderator; wiec mogłoby być tak że moderator Ci coś skazuje i jednocześnie odobserwuje wątek; więc trzeba by o tym pamiętać.

**Comment by adam-boduch** [comment]
Tak, komentarze oraz obserwowanie to nie odrębne rzeczy. Można dodać komentarz i nie obserwować wpisu. 

P.S. Automatyczne obserwowanie po napisaniu komentarza działa tylko gdy zaznaczona jest odpowiednia opcja w profilu.

**Comment by olekstomek** [comment]
Dzięki za odpowiedzi. Wszystko jasne. 👍
