### ISSUE TITLE
Missing argument 3 for Illuminate\Session\DatabaseSessionHandler::__construct() podczas uruchomienia

### ISSUE THREAD

**Issue by bkielbasa** [adam-boduch/coyote#77]
Hej,

próbowałem uruchomić coyote u mnie lokalnie, ale dostałem taki błąd jak wyżej.
PHP v7 z wbudowanym serwerem.

**Comment by adam-boduch** [comment]
Wyglada na to, ze dodali w samym frameworku nowy parametr, ktorego wczesniej nie bylo.

**Comment by adam-boduch** [comment]
Dzięki za poprawkę.

**Comment by bkielbasa** [comment]
Jakieś 2 dni temu https://github.com/laravel/framework/commit/00f4cab7b65a85314204d800a47c669b1689a26c
