### ISSUE TITLE
Link nic nie robi, nie prowadzi nigdzie.

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#80]
Przykładowa strona z [linkiem](http://dev.4programmers.info/Forum/Newbie?page=0)
Zauważyłem też że w stopce nie działają linki - tzn działają, ale jest 404.
> http://dev.4programmers.info/Forum/Newbie/Mark
<img width="377" alt="scr1" src="https://cloud.githubusercontent.com/assets/5124712/16966889/ea1b83ee-4e06-11e6-879d-b9caf960ae6b.PNG">

**Comment by adam-boduch** [comment]
Klikniecie na ten link oznacza watki jako przeczytane. Wysylane jest zadanie AJAX.
