### ISSUE TITLE
Kolejny nie działający link

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#81]
Na tej [stronie](http://dev.4programmers.info/Profile/41)

na dole jest zakładka "Posty na forum" - nie działa. Console.log nic nie wypluwa, zero reakcji, podmienia się tylko hash w url'u

<img width="308" alt="scr2" src="https://cloud.githubusercontent.com/assets/5124712/16967342/c37eae26-4e08-11e6-8112-6b1d5603f2de.png">

**Comment by adam-boduch** [comment]
Racja, skupmy sie poki co na samym forum, bo ono jest w 100% skonczone :)
