### ISSUE TITLE
Sekcja "popularne tagi" nie aktualizuje się

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#83]
Możliwe że masz ustawione w kodzie jakieś cache'owanie tego przez jakiś czas, lub jakieś przeliczanie odpalane np w cronie.

Ale dodając posta z przykładowym tagiem php - podczas tagowania pokazywało mi poprawnie podpowiedź(że są 3 posty z takim tagiem) natomiast po dodaniu, w sekcji "popularne tagi" nadal widzę żę php ma tylko jedynkę na liczniku.
<img width="920" alt="scr4" src="https://cloud.githubusercontent.com/assets/5124712/16967642/4eb63e4a-4e0a-11e6-9671-e56fb5100bad.png">

**Comment by adam-boduch** [comment]
To prawda, ta sekcja jest cachowna i odswiezana co 30 min o ile dobrze pamietam.
