### ISSUE TITLE
Załącznik w formacie PNG

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#84]
Wiem że na liście akceptowanych formatów nie ma go - ale może by dać support dla png w załącznikach postów?. Ewentualnie komunikat ze nie obsługujemy tego formatu, bo obecnie jest tylko komunikat że pole attachment jest wymagane.
<img width="704" alt="scr5" src="https://cloud.githubusercontent.com/assets/5124712/16967787/25323816-4e0b-11e6-9740-782fbd463bbd.png">

**Comment by adam-boduch** [comment]
Sprawdziłem i załacznik PNG działa normalnie. Mozesz tutaj zalaczyc ten plik PNG ktory probowales dodac?

**Comment by axelbest** [comment]
![bigimidz](https://cloud.githubusercontent.com/assets/5124712/17086087/af3f39b4-51e9-11e6-8d41-c8801615285d.png)

**Comment by adam-boduch** [comment]
Poprawione
