### ISSUE TITLE
Nie można zapisać zmian w ustawieniach konta

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#87]
W przypadku zmiany ustawień konta - niemożliwe jest ustawienie czegokolwiek. Email użytkownika trzeba by było wykluczyć z puli maili do sprawdzenia.
<img width="766" alt="scr8" src="https://cloud.githubusercontent.com/assets/5124712/17086195/4954e3ee-51ec-11e6-93c9-fadf968bcdf9.png">

**Comment by adam-boduch** [comment]
A czy aby na pewno ten email nie jest przypisany do innego konta ktory zalozyles? Oczywiscie sprawdze to, ale powinno dzialac to w ten wlasnie sposob - niemozliwe powinno byc przypisanie tego samego adresu do innego uzytkownika.

**Comment by adam-boduch** [comment]
Nie odpisales na moj poprzedni komentarz wiec uznaje, ze tak jak napisalem - adres e-mail byl przypisny do innego konta. Zamykam wiec.
