### ISSUE TITLE
Błędne linki w mailach z powiadomieniami

### ISSUE THREAD

**Issue by axelbest** [adam-boduch/coyote#99]
https://dev.4programmers.info/Forum/Off-Topic/75-watek_nr3?p=246#id246

W mailach otrzymuje taki link
```
Kliknij, aby przeczytać post: http://localhost/Forum/Off-Topic/75-watek_nr3?p=245#id245
```
Maile wpadają też do spamu (poczta o2.pl)

**Comment by adam-boduch** [comment]
Czy teraz ze spamem jest ok?

**Comment by axelbest** [comment]
Teraz jest ok - maile nie wpadają tam. Widziałem że adresy też poprawne są w mailach. Można zamykać.
